### ISSUE TITLE
Can't connect behind proxy (was: appcenter login Error)

### ISSUE THREAD

**Issue by PuffTMD** [microsoft/appcenter-cli#636] opened 2019-08-17 14:19 UTC
version: appcenter version 2.1.1

When attempting to appcenter login, the command succesfully loads the webiste and the token generated is pasted into the terminal but we are presented with the following error.

Error: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80

**Comment by PuffTMD** [comment] 2019-08-17 14:36
Also tried:
Using the --token parameter:

    Create a Full Access API token (See steps 1-5).
    Open a terminal/command window.
    Add the --token switch to the CLI command you are running. For example, run appcenter apps list --token {API-token} to get a list of your configured applications.

# appcenter profile list --token <takenvalue>
Error: Command 'profile list --token <token value> failed with exception "tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80"

**Comment by owenniblock** [comment] 2019-09-04 07:05
Please can you rerun the login with `--debug` and post the output here (removing any sensitive information).

**Comment by ManilTester** [comment] 2019-09-25 19:46
Hi,

i am facing the same issue. I have executed command : appcenter login {token}. I got the the token from the new browser link. 

Debug log : 

C:\Users\manil.kapoor\AppData\Roaming\npm>appcenter login --debug --token 888e7b06337016d48e8f14ab0be2f1ca5a8f99b8
Using appcenter-cli version: 2.1.2
| Getting user info ...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/user",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.1.2 NodeJS/v10.0.0 win32/10.0.16299",
    "x-api-token": "888e7b06337016d48e8f14ab0be2f1ca5a8f99b8",
    "internal-request-source": "cli",
    "diagnostic-context": "bcd85bc4-7d0d-4ea0-affe-8ac4e1201f3e",
    "cli-command-name": "login"
  },
  "body": null
}
/ Getting user info ...Error from response, message: connect ETIMEDOUT 104.209.152.237:443
/ Getting user info ...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/user",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.1.2 NodeJS/v10.0.0 win32/10.0.16299",
    "x-api-token": "888e7b06337016d48e8f14ab0be2f1ca5a8f99b8",
    "internal-request-source": "cli",
    "diagnostic-context": "bcd85bc4-7d0d-4ea0-affe-8ac4e1201f3e",
    "cli-command-name": "login"
  },
  "body": null
}
- Getting user info ...Error from response, message: connect ETIMEDOUT 104.209.152.237:443
- Getting user info ...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/user",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.1.2 NodeJS/v10.0.0 win32/10.0.16299",
    "x-api-token": "888e7b06337016d48e8f14ab0be2f1ca5a8f99b8",
    "internal-request-source": "cli",
    "diagnostic-context": "bcd85bc4-7d0d-4ea0-affe-8ac4e1201f3e",
    "cli-command-name": "login"
  },
  "body": null
}
\ Getting user info ...Error from response, message: connect ETIMEDOUT 104.209.152.237:443
Error: connect ETIMEDOUT 104.209.152.237:443


Note: My company has proxy settings ,can this be an issue for loggin into appcenter

**Comment by jpeg-ms** [comment] 2019-10-04 04:50
It is quite likely due to a proxy error. We've seen this in #536 as well. We have not tested this ourselves yet.

**Comment by jerietve** [comment] 2019-10-22 05:25
The error basically says the App Center CLI (Node) is unable to reach appcenter.ms (104.209.152.237) over HTTPS (port 443). Your browser goes to the same place to get the token, but it must have been set up to respect the proxy set up by your companies.

I tried to reproduce this by blocking Node.js in the firewall but did not get the same error yet.

I imagine you get the same error when running any other `appcenter` command with the `--token` parameter, because the CLI is just not able to get a connection set up through the proxy.

**Comment by ahbilal-ms** [comment] 2019-10-31 01:23
@PuffTMD @ManilTester We are investigating the issue and will appreciate your response on the below:

1. Are you migrating from HockeyApp?
2. Was the command working before or this is the first time you are using this command? If it was working before, what tools/functions were you using before?

**Comment by PuffTMD** [comment] 2019-11-12 08:08
@ahbilal-ms 
1. Not migrating
2. first time for me.

**Comment by russelarms** [comment] 2021-02-18 09:41
I haven't managed to reproduce the issue for the current version (2.7.4), so I'm closing this. Feel free to reopen it if you have any updates about it.

**Closed by russelarms** 2021-02-18 09:41 UTC
Labels: bug
