### ISSUE TITLE
Uploading Correlation ID

### ISSUE THREAD

**Issue by Vacxe** [microsoft/appcenter-cli#1260] opened 2021-02-03 23:19 UTC
### **Description**

Due uploading though the CLI I received this issue (second time). Appcenter cli is a part of our CI pipe line and uploaded build definitely is unique. Probably the issue coming from backend side but unfortuynalelly I can't find a right place to create and issue.

### **Repro Steps**
I can't provide specific apks, but it start happens 4-5 days ago. And also it happen time to time.

### **Expected behavior**
Apk will be uploaded property to appcenter

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - e.g. `appcenter tokens list`
2. Which version of the App Center CLI are you using?
     2.7.3
3. Which OS version did you experience the issue on?
    Linux
4. What version of Node.js and NPM/Yarn are you using?
    - node:15.3.0-alpine3.10 docker image

````Error: Loading release id failed: A problem occured while extracting your app. (Correlation ID: <UIDD>)
17:41:30
  Response: Error: Loading release id failed: A problem occured while extracting your app. (Correlation ID: <UIDD>)
````

**Comment by russelarms** [comment] 2021-02-04 07:34
Hi @Vacxe, thanks for reaching out. Please, fill in the issue according to the [bug report template](https://github.com/microsoft/appcenter-cli/issues/new?assignees=&labels=&template=bug_report.md&title=).

**Comment by russelarms** [comment] 2021-02-05 07:43
@Vacxe thank you.
Could you check whether CLI fails to upload this specific apk every time or it happens occasionally?
Is it possible for you to check whether you can upload this apk to the portal through a browser?

**Comment by Vacxe** [comment] 2021-02-06 10:01
@russelarms yea. It possible to upload the same apk (exactly the same artifact) via web version. If u require any additional info for investigation please let me know.

**Comment by Jamminroot** [comment] 2021-02-09 10:35
Hey @Vacxe, would you mind sharing correlation id with us? That would help us understand what is going wrong during the upload process.

**Comment by Vacxe** [comment] 2021-02-12 02:51
@Jamminroot `f79fd1ba-f306-4fa3-859b-014bdec901ea`

**Comment by Jamminroot** [comment] 2021-02-12 08:37
Is there any other cases - for example, app transfer, or other critical changes?
Also, is it possible that there's a typo in correlationId - since I can't really find a transaction on the backend related to the one you provided.

**Comment by Jamminroot** [comment] 2021-02-15 07:38
Is there a chance for you to gather debug logs? For that you'd need to add `--debug` argument to the command.
Also, having additional debug logs from npx should help, but that would require different invocation, example is below:
`DEBUG="appcenter-cli:commands:*" npx ts-node src/index.ts distribute releases list`
And can you share the command you are using to upload?

**Comment by PetrBodnar** [comment] 2021-02-15 10:46
### **Description**
We got similar problem with uploading iOS builds in our CI (we are using appcenter-cli).
Sometimes uploading is ok, sometimes - we have error 
`Loading release id failed: A problem occured while extracting your app.`
We then can upload built ipa manually without problem. Often another build from same commit uploads normally.

Correlation ids: 18711d30-da7d-4d0d-b349-532fe457d1c1, 15723071-c248-42c5-bb04-9311dc7a5f6b, bdd785a1-ce23-4682-ac77-af2bb9abf04b

### **Repro Steps**
Cannot reproduce, occurs often, randomly. 

### **Expected behavior**
We expect that build uploads without errors



1. Is there a particular beacon/command that you are having trouble with?
    `appcenter distribute release --app APP_NAME --file path/to/appcenter.ipa --token TOKEN --group Collaborators --disable-telemetry --debug --release-notes 'RELEASE_NOTES'`
2. Which version of the App Center CLI are you using?
    2.7.3
3. Which OS version did you experience the issue on?
  mac OS Catalina 10.15.6
4. What command line/shell are you using?
    GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
5. What version of Node.js and NPM/Yarn are you using?
    node v14.1.0, npm 6.14.4


(May be related to https://github.com/microsoft/fastlane-plugin-appcenter/issues/243 ?)

**Comment by alexandergoncharov** [comment] 2021-05-26 15:59
Hi all,

We implemented a fix for preventing this issue again.
@Vacxe , @PetrBodnar , could you please let us know if you still have this issue or not?

**Comment by Vacxe** [comment] 2021-05-26 23:44
Thanks @alexandergoncharov . I let you know in case of reproduce. Cheers.

**Comment by alexandergoncharov** [comment] 2021-07-19 10:14
Hi all,

@Vacxe , @PetrBodnar, just a friendly ping if this issue is still reproducible? :)

**Comment by PetrBodnar** [comment] 2021-07-19 10:23
Looks like it is ok now (issue is not reproduces any more), thank you :)

**Comment by alexandergoncharov** [comment] 2021-07-19 10:36
Awesome, Thanks for letting us know!

So, I'm going to close this issue now but please feel free to ask any questions or let us know if you faced this issue again.

**Closed** 2021-07-19 12:08 UTC
Labels: question

**Comment by philj0st** [comment] 2023-02-09 07:52
I'm facing the same issue. Was the fix in the cli or the backend? @alexandergoncharov-zz

**Comment by MikhailSuendukov** [comment] 2023-02-09 13:33
Hello @philj0st , do you get exactly the same error as in the description? It would be helpful if you could provide the command that produces the error and the corresponding logs.

**Comment by bassemelmokhtar** [comment] 2023-05-09 12:13
For me, I fixed this issue when I changed the Release type to Beta from Entreprise in my App Settings in Appcenter.

I hope this helps you as well.
