### ISSUE TITLE
appcenter error when executing

### ISSUE THREAD

**Issue by rvinc66** [Microsoft/appcenter-cli#377] opened 2018-02-01 18:29 UTC
When I enter appcenter at the command line I receive this error:

appcenter
module.js:471
    throw err;
    ^

Error: Cannot find module '../dist/util/commandline'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ron\vsac\appcenter-cli\bin\appcenter.js:47:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Yes, I installed it via npm as the instructions indicate.

**Comment by rvinc66** [comment] 2018-02-02 20:17
5.6.0

**Comment by rvinc66** [comment] 2018-02-04 02:03
1.0.3

**Comment by christav** [comment] 2018-02-06 01:15
@rvinc66 What platform (os & version) are you installing on? I'm not able to reproduce this here, so more info would help tracking this down.

**Comment by rvinc66** [comment] 2018-02-20 13:27
Windows 10

**Comment by amchew** [comment] 2018-03-09 20:42
Thanks @rvinc66 for bringing this to our attention, glad that it works now, and @christav for working on this! I'll be closing this issue.

**Closed by amchew** 2018-03-09 20:42 UTC
