### ISSUE TITLE
Distribute release doesn't work with Node v15.0.1

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/appcenter-cli#1405] opened 2021-05-05 09:03 UTC
### **Description**
`appcenter distribute release` yields "distribute release is invalid"
`appcenter distribute` yields
```
Commands:
    groups               Commands for manipulating distribution groups
    releases             Commands for manipulating releases for your application
    stores               Commands to distribute to stores (App Store, Google Play, Intune)
    release              Unable to load C:\Users\[MYUSERNAME]\AppData\Roaming\nvm\v15.0.1\node_modules\appcenter-cli\dist\commands\distribute\release.js to read help
```

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Run `appcenter distribute release`

### **Expected behavior**
Should publish release.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter distribute release`
2. Which version of the App Center CLI are you using?
    - 2.9.0
3. Which OS version did you experience the issue on?
    - Windows 10 version 20H2
4. What command line/shell are you using?
    - powershell
5. What version of Node.js and NPM/Yarn are you using?
    -node v15.0.1, npm 7.0.3.
6. **It works with node 14.16.1 and npm 6.14.12**

**Comment by AnastasiaKubova** [comment] 2021-05-07 06:50
Hi! Thanks for getting in touch with us! I checked this behavior with the node version `15.0.1` and for me all worked correctly.
I can suspend that this problem related to the settings of the local environment, not `appcenter-cli`.
Could you please clarify does this issue happen only with this `appcenter distribute` command or with other commands too? Could you please try to clean the cache of your project (for example via `git clean -dfx`), clean node cache (`npm cache clean --force`) and try again?

**Comment by MihaMarkic** [comment] 2021-05-07 09:04
Hi @AnastasiaKubova 

It happened only with `distribute release` command, not others. It's not a big deal since I can change node version easily. But will try to gather more info if possible in the future.

**Comment by AnastasiaKubova** [comment] 2021-05-07 09:24
I got it. Then I am closing this issue for now, because from our side we weren't able to reproduce this issue, but feel free to reopen this issue if you will have additional information.

**Closed by AnastasiaKubova** 2021-05-07 09:24 UTC
