### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by grndvl1** [microsoft/appcenter-cli#1217] opened 2021-01-15 21:32 UTC
CLI, what a mess worst error reporting ever.  Trying to upload with command I get this lovely error.  File is there as when I use it in Open API it is able to upload 

`App
Center
CLI
would
like
to
collect
data
about
how
users
use
CLI
commands
and
some
problems
they
encounter.
Participation
is
voluntary
and
when
you
choose
to
participate
your
device
automatically
sends
information
to
Microsoft
about
how
you
use
App
Center
CLI.

For
more
information,
please
see
our
privacy
policy
at
https://aka.ms/mobilecenterprivacy

? Enable telemetry?  (Y/n) ? Enable telemetry?  (Y/n) ? Enable telemetry?  (Y/n) | Loading prerequisites.../ Loading prerequisites...- Loading prerequisites...Error: failed to create release upload for /home/circleci/repo/Sprint.apk. Not found. Correlation ID: e982f78a-c3ee-4170-816d-a5f2c3a8231f

Exited with code exit status 3`

  I have so many questions.  Using -app it requires me to add the userid from appcenter otherwise it fails.  Our app name has - dashes in it and this might be messing up.  on group I can have more than one group to set.  Why do I need userid in -app when I am using the appcenter token?  Supposedly if I have APPCENTER_API_TOKEN variable set on Circleci I don't need it in the command, well you do otherwise it errors.  We have a legacy group from Hockey called "Tag: our-qa", well guess what setting this in --group, it fails.  There is soooo much wrong with CLI, why are you wanting us to use this garbage when open API was sooooooo much better?

    appcenter distribute release \
        --app "my_appcenter_id/${APP_NAME}" \
        --group Collaborators \
        --file "${FULL_APP_PATH}" \
        --token "${APPCENTER_API_TOKEN}" \
        --debug

Please fix this garbage

**Comment by grndvl1** [comment] 2021-01-19 17:44
CLI is broken for our project it looks like to use the upload.  Not sure why but testing out in postman gives me a 404 error that it can't find the project even though I can upload it using the current API that you are killing.

**Comment by russelarms** [comment] 2021-01-26 13:17
Hi, @grndvl1, sorry you are experiencing issues.

Regarding the telemetry question format: it's working fine for me, could you share some information about the environment (os, terminal, node, npm versions) where you're experiencing this issue?

> Why do I need userid in-app when I am using the appcenter token?

This is likely because users can share access to their applications with other users.  In this case, `appcenter apps list` will show something like
```
yourUserId/AppName
otherUserId/AppName
```

> Our app name has - dashes in it and this might be messing up.

Could you please describe the dash problem in more detail?

> We have a legacy group from Hockey called "Tag: our-qa", well guess what setting this in --group, it fails.

Have you tried escaping space char (`\ ` on macOS)?

> Not sure why but testing out in postman gives me a 404 error that it can't find the project even though I can upload it using the current API that you are killing.

Can you please file a support ticket with us so we can look into your specific issues and logs? https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us

**Comment by russelarms** [comment] 2021-01-26 13:19
> CLI is broken for our project, it looks like, to use the upload. Not sure why but testing out in postman gives me a 404 error that it can't find the project even though I can upload it using the current API that you are killing.

JFYI we have an updated instruction on the new API: https://docs.microsoft.com/en-us/appcenter/distribution/uploading#upload-new-release

**Comment by grndvl1** [comment] 2021-03-17 17:49
@russelarms I ran into this and the problem was that my app was part of a company.  And then I had 2 groups to distribute to.  
 ```
LATEST_VERSION="$(appcenter distribute releases list --app $OrganizationName/$APP_NAME --token ${APPCENTER_API_TOKEN} | grep ID | head -1 | tr -s ' ' | cut -f2 -d ' ')"
echo "LATEST_VERSION2=$LATEST_VERSION"
appcenter distribute releases add-destination -a $OrganizationName/$APP_NAME -d "OurTesters" -t group -r $LATEST_VERSION --token ${APPCENTER_API_TOKEN} --debug --disable-telemetry

```

**Comment by AnastasiaKubova** [comment] 2021-03-23 08:24
Hello, @grndvl1 ! 
I am trying to reproduce your issue but for me all work correctly. Could you please clarify some details:
- Which version of App Center CLI are you use?
- You can't upload release only to the `Collaborators` group or to any group? Group is public or private?
- Did you try to perform command from your description without `\` symbols?
- It doesn't work only for a specific app or for all apps?
- Could you please share logs (please make sure before sending logs that they don't contain personal information)? If you can't share logs here you can open a support ticket https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us.

**Comment by grndvl1** [comment] 2021-03-23 20:39
Seems it was a hiccup in your system or CircleCI.  I think it was at a time when appcenter was having issues.  No longer an issue.

**Comment by AnastasiaKubova** [comment] 2021-03-24 05:50
Glad to hear that your problem was resolved. I'm closing this issue but feel free to reopen this issue if you have additional questions.

**Closed by AnastasiaKubova** 2021-03-24 05:50 UTC
Labels: Distribute, question
