### ISSUE TITLE
zsh: command not found: appcenter

### ISSUE THREAD

**Issue by vksgautam1986** [microsoft/appcenter-cli#2467] opened 2023-12-07 11:29 UTC
### **Description**
Please describe the issue you are facing using the CLI.
i have used this command -- npm install --location=global appcenter-cli

i am using MAC M1 chip and nvm along with it and having this issue of "zsh: command not found: appcenter "
zsh: command not found: appcenter

node -- default -> 18.1.0 (-> v18.1.0)

**Comment by MikhailSuendukov** [comment] 2023-12-07 15:29
Hello @vksgautam1986 and thanks for reaching out to us, it seems your problem is related to your nvm setup. For a more detailed investigation, it would be great to get the appcenter-cli installation logs.

**Comment by MikhailSuendukov** [comment] 2023-12-08 12:54
Hi, it seems that your problem is duplicate of https://github.com/microsoft/appcenter-cli/issues/460, so i will close this issue, but if you still have some questions feel free to reopen it.

**Closed by MikhailSuendukov** 2023-12-08 12:54 UTC

**Comment by vksgautam1986** [comment] 2023-12-18 13:05
netsmartz@Netsmartzs-Mac-mini ~ % yarn global add appcenter-cli
yarn global v1.22.19
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "appcenter-cli > webpack-cli@4.9.2" has unmet peer dependency "webpack@4.x.x || 5.x.x".
warning "appcenter-cli > webpack-cli > @webpack-cli/configtest@1.2.0" has unmet peer dependency "webpack@4.x.x || 5.x.x".
[4/4] 🔨  Building fresh packages...
success Installed "appcenter-cli@2.14.0" with binaries:
      - appcenter
✨  Done in 2.11s.
netsmartz@Netsmartzs-Mac-mini ~ % - appcenter
zsh: command not found: appcenter
netsmartz@Netsmartzs-Mac-mini ~ %

**Comment by AnatolyPristensky** [comment] 2023-12-18 14:45
@vksgautam1986, this is definitely issue with your local environment, I've tried to install appcenter-cli via yarn, and all works as expected:

```
anatoly@MacBook-Pro ~ % yarn global add appcenter-cli
yarn global v1.22.19
warning package.json: No license field
[1/4] 🔍  Resolving packages...
warning appcenter-cli > ms-rest > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "appcenter-cli > webpack-cli@4.9.2" has unmet peer dependency "webpack@4.x.x || 5.x.x".
warning "appcenter-cli > webpack-cli > @webpack-cli/configtest@1.2.0" has unmet peer dependency "webpack@4.x.x || 5.x.x".
[4/4] 🔨  Building fresh packages...
success Installed "appcenter-cli@2.14.0" with binaries:
      - appcenter
✨  Done in 21.28s.
anatoly@MacBook-Pro ~ % appcenter -v
appcenter version 2.14.0
```

Please make sure that your ZSH configured properly.

**Comment by vksgautam1986** [comment] 2023-12-21 11:53
Hi @AnatolyPristensky. Here is my  profile.i have tried things but it did not worked out

alias node16='export
PATH="/usr/local/bin:/usr/local/opt/node@16/bin:$PATH"; node -v'
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/2.7.0/bin:$PATH"
export PATH=$PATH:/Users/netsmartz/Library/Android/sdk/platform-tools
export PATH="/opt/homebrew/Cellar/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This load$

**Comment by vksgautam1986** [comment] 2023-12-21 12:04
thanks guys its looks like its working fine now. 

i tried with this command --  npm install -g appcenter-cli
after that i ran the app center command , it returned--
--

Visual Studio App Center helps you build, test, distribute, and monitor mobile apps.
Version 2.14.0

Usage: appcenter <command>

Commands:
    analytics                      View events, audience info, sessions, and  
                                   other analytics for apps                   
    apps                           View and manage apps                       
    build                          Start builds, get their status, and        
                                   download artifacts                         
    codepush                       View and manage CodePush deployments and   
                                   releases                                   
    crashes                        Upload symbols for better crash reports    
    distribute                     Send builds to testers and manage          
                                   distribution groups                        
    orgs                           Manage organizations                       
    profile                        Manage your profile                        
    telemetry                      Manage telemetry preferences               
    test                           Start test runs and get their status       
    tokens                         Manage API tokens                          
    help                           Get help using appcenter commands          
    login                          Log in                                     
    logout                         Log out                                    
    setup-autocomplete             Setup tab completion for your shell
