### ISSUE TITLE
codepush release-react Error:The asset cannot be uploaded. Try creating a new one

### ISSUE THREAD

**Issue by galiullinairat** [microsoft/appcenter-cli#1723] opened 2021-11-09 11:27 UTC
### **Description**
On uploading:
_Error: The asset cannot be uploaded. Try creating a new one_ 
It worked perfectly 1-2 weeks ago 
### **Repro Steps**
1. appcenter codepush release-react -a username/appname -d Production

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
**appcenter codepush release-react**
2. Which version of the App Center CLI are you using?
**appcenter version 2.10.4**
3. Which OS version did you experience the issue on?
**macOS BigSur 11.6.1**
4. What command line/shell are you using?
**zsh**
5. What version of Node.js and NPM/Yarn are you using?
**node v14.17.3, npm 6.14.13**
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.

**Comment by puneetkansal04** [comment] 2021-11-09 11:36
Same her not able to detect the problem

**Comment by GaraGentor** [comment] 2021-11-09 11:42
I just wanted to open the same Issue now. Since today I have the same Problem. I tried to downgrade appcenter-cli to v2.5.4 and update to latest version. I also tried to upload everything manually by creating the CodePush folder with all assets and upload. But sadly that failed too. My last working upload was on 2. November where everything worked and suddenly 'Error: The asset cannot be uploaded. Try creating a new one Appears'. Im running on node 14.11.0. and Appcenter 2.10.4.

https://status.appcenter.ms/
Seems to be fine there

**Comment by Neungzad** [comment] 2021-11-09 11:45
I just found this issue as well. is it possible about the AppCenter server ?

**Comment by GaraGentor** [comment] 2021-11-09 11:46
<img width="868" alt="Bildschirmfoto 2021-11-09 um 12 45 43" src="https://user-images.githubusercontent.com/39561325/140918519-720ac10c-90b5-4b15-a2c2-f4d866d2ad0b.png">

I just saw that. I checked this 5 minutes ago and it wasnt updated. Maybe they have some work in progress to maintain.

Link is provided at my earlier post.

**Comment by galiullinairat** [comment] 2021-11-09 12:37
it seems some problem with appcenter serverside. Let's wait...

**Comment by DmitriyKirakosyan** [comment] 2021-11-09 17:47
Hi guys, sorry for the inconvenience. This was caused by some planned work on the backend side. It should work now.
Closing the issue. Please let me know if someone still experiences this error.

**Closed by DmitriyKirakosyan** 2021-11-09 17:47 UTC

**Comment by Harikarthyk** [comment] 2023-08-03 08:36
Might help a few people:
I too got this error when I tried with mobile internet, but when I switched to my office wifi, It was working fine.
