### ISSUE TITLE
Timeout error at release distribution 

### ISSUE THREAD

**Issue by mcanzerini** [microsoft/appcenter-cli#2283] opened 2023-04-13 11:25 UTC
Hi, 

We cannot distribute releases through the `appcenter-cli` for 5 days.

The error message is pretty weird: 

```
Error: Command 'distribute release --app <myapp> --file <my.ipa> --group TEST --token xxx --release-notes release notes' failed with exception "request to https://api.appcenter.ms/v0.1/apps/xxx/xxx/uploads/releases failed, reason: connect ETIMEDOUT 13.107.237.45:443"
``` 

cli version : `v2.13.4`

This happens since April the 8th through our CI/CD pipelines. We are behind a firewall proxy on Windows Server machine. Maybe an IP that has changed and we have to whitelist it?

Any help on this? 

Thanks a lot

**Comment by MikhailSuendukov** [comment] 2023-04-13 13:22
Hi @mcanzerini it seems this is a duplicate of https://github.com/microsoft/appcenter/issues/2539. I will close this issue, if you have any questions you can either reopen this issue or write them in that issue.

**Closed by MikhailSuendukov** 2023-04-13 13:22 UTC

**Comment by mcanzerini** [comment] 2023-04-13 13:38
Sorry but it seems that the issue you mentionned is about `code-push`. 
In my case, this is the `distribute release` command that causes the timeout

**Comment by MikhailSuendukov** [comment] 2023-04-13 13:55
Yes, but the fact is that, as I described in my comment in that issue, AppCenter code push service is experiencing some issues due to overload right now.

**Comment by sonhd92** [comment] 2023-05-05 04:44
@mcanzerini Hi, did you found he soulution? I'm getting this issue while using `appcenter distribute` too

**Comment by mcanzerini** [comment] 2023-05-05 06:44
Do you use appcenter behind a WAF ?

I think appcenter has added some new servers with new IP addresses behind api.appcenter.ms. 
As we work by whitelist, I resolved my issue by autorize the new IP adresses.

**Comment by sonhd92** [comment] 2023-05-09 04:15
@mcanzerini I used my company network so I think there is a WAF. But how can you get the IP address of api.appcenter.ms?

**Comment by lucen-ms** [comment] 2023-05-09 13:23
Please contact our customer support so we can check logs for your cases.
