### ISSUE TITLE
Invalid deployment name when it contains a `/` (forward slash)

### ISSUE THREAD

**Issue by allisothebys** [microsoft/appcenter-cli#1792] opened 2022-01-17 16:47 UTC
### **Description**
Hi.

We are currently using codepush to create deployments for each branch and we use the current branch name as the deployment name.

The command we use the following 
`appcenter codepush deployment add -a <ownerName>/<appName>  --token $BRANCH_NAME`

When the branch name contains a `/` (forward slash) e.g. `feature/my-new-feature` the command fails with
`[{"field":"name","message":"Field is invalid"}]`

Not 100% sure this is a bug, but I didn't find any documentation regarding allowed names for the deployment

W
### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Create a brand new app name
2. Add a user token
3. Run the command `appcenter codepush deployment add -a <ownerName>/<appName>  --token test/this-will-fail`

### **Expected behavior**
Expected the command to succeed and a deployment with name `test/this-will-fail` to be created

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - appcenter codepush deployment
2. Which version of the App Center CLI are you using?
    - appcenter version 2.10.8
3. Which OS version did you experience the issue on?
    - macoS Monterey 12.1
4. What command line/shell are you using?
    - default macOS terminal, zsh
5. What version of Node.js and NPM/Yarn are you using?
    - npm version 8.3.0, node version v17.3.0
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command, for example, `DEBUG="appcenter-cli:*" appcenter apps list`. Include the logs here, don't forget to **omit** any personal/sensitive data.
 See https://gist.github.com/allisothebys/86a2660e575877a09fcb142a17acdd99

**Comment by DmitriyKirakosyan** [comment] 2022-01-19 23:14
Hi @allisothebys , thank you for reaching out to us!
We are currently investigating this issue. I will updated you on the progress.

**Comment by DmitriyKirakosyan** [comment] 2022-01-31 09:30
Hi @allisothebys , we filed a bug on our board. It will be addressed on the backend side, but no ETA at this moment.

**Comment by allisothebys** [comment] 2022-02-04 11:26
@DmitriyKirakosyan Thanks for the update 👍

**Comment by allisothebys** [comment] 2022-04-12 22:33
Any update to share? @DmitriyKirakosyan

**Comment by DmitriyKirakosyan** [comment] 2022-04-14 06:54
Unfortunately, no updates. The team is busy with other high priority tasks.

**Comment by DmitriyKirakosyan** [comment] 2022-07-22 12:35
Hi @allisothebys , actually, this is not a bug, but a feature we don't support.
We are not planning to add this functionality, so I'm closing it as an expected behaviour.
I'll update the command description to make it visible and clear from the command line.

**Closed by DmitriyKirakosyan** 2022-07-22 12:35 UTC

**Comment by allisothebys** [comment] 2022-08-31 21:06
Thank you for the clarification 👍
