### ISSUE TITLE
appcenter distribute fails silently behind proxy

### ISSUE THREAD

**Issue by mcanzerini** [microsoft/appcenter-cli#2333] opened 2023-05-25 08:15 UTC
### **Description**
`appcenter distribute` fails silently when I set proxy using HTTP_PROXY environment variable. It does not print any message but I do not see the release in appcenter.

If I add `--debug` option to the command, I see those logs:

```
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/MyORG/MyApp/distribution_groups/TEST/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.13.4 NodeJS/v16.17.0 win32/10.0.14393",
    "x-api-token": "xxxx"
  },
  "body": null,
  "strictSSL": false,
  "agent": {
    "options": {
      "proxy": {
        "host": "my.proxy.xyz",
        "port": 80,
        "protocol": "http:"
      }
    },
    "proxyOptions": {
      "host": "my.proxy.xyz",
      "port": 80,
      "protocol": "http:"
    },
    "maxSockets": null,
    "requests": [],
    "sockets": [],
    "_events": {},
    "_eventsCount": 1
  }
}
Error from response, message: tunneling socket could not be established, statusCode=405
```

Can anyone help me on this error ?

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    `appcenter distribute release`
2. Which version of the App Center CLI are you using?
    v 2.13.4
3. Which OS version did you experience the issue on?
    Windows Server
4. What command line/shell are you using?
    PowerShell

**Comment by mcanzerini** [comment] 2023-05-25 12:56
The error was a bad proxy configuration.
But there is still a bug to my mind as appcenter distribute must fail with non 0 exit code

**Comment by AnatolyPristensky** [comment] 2023-05-25 13:47
Hello @mcanzerini, could you please share an actual error message?

**Comment by mcanzerini** [comment] 2023-05-25 13:49
When the proxy is not well configured, the `appcenter distribute` command does not raise any error and does not log anything, but nothing is distributed in app center. With debug option, I see the error log, but the command does not exit with error code.

**Comment by AnatolyPristensky** [comment] 2023-05-26 07:21
@mcanzerini I suppose that the issue is in your network configuration. `statusCode=405` usually indicates client-side issues, so I suggest to contact your system administrator. I'm closing this issue, but feel free to reopen it in case of new information.

**Closed by AnatolyPristensky** 2023-05-26 07:21 UTC
