### ISSUE TITLE
Unknown argument --no-duplicate-release-error

### ISSUE THREAD

**Issue by carloscuesta** [Microsoft/appcenter-cli#364] opened 2018-01-16 13:21 UTC
Hello!

I'm trying to use the `--no-duplicate-release-error` argument as stated in the docs to prevent the release command throwing an error when there's an identical bundle uploaded, but seems that it's not recognized as a valid option

```
$ appcenter codepush release-react -a app/org -d Staging --no-duplicate-release-error
```

**Comment by sergey-akhalkov** [comment] 2018-01-17 13:42
Hi @carloscuesta, thanks for submitting the issue, I was able to reproduce it and currently working on solution and I will let you know if I have any updates.

**Comment by carloscuesta** [comment] 2018-01-17 15:33
Thanks good to kno! @sergey-akhalkov

**Comment by sergey-akhalkov** [comment] 2018-01-18 12:49
Hi @carloscuesta, here is the fix https://github.com/Microsoft/appcenter-cli/pull/367 - please take a look at it and let me know if you see any issues or have any questions.

PS: `--no-duplicate-release-error` flag has been renamed to the `--disable-duplicate-release-error` because of this issue https://github.com/substack/minimist/issues/123

**Comment by carloscuesta** [comment] 2018-01-18 14:50
Everything works fine I've tested your fix! 

Thanks @sergey-akhalkov

**Comment by sergey-akhalkov** [comment] 2018-01-18 15:30
@carloscuesta, great! Please let me know if you see any other issues or have any questions.

**Comment by christav** [comment] 2018-01-24 00:07
I merged #367, should release sometime this week.

**Comment by saraht129** [comment] 2018-01-26 05:40
Hi there, I'm getting the same thing with the `--sourcemap-output`. It returns `Unknown arguments` no matter what value I pass in. Could this be the same issue?

**Comment by carloscuesta** [comment] 2018-01-26 07:35
It is @saraht129. The error has been fixed but not released yet.

**Comment by christav** [comment] 2018-01-29 19:06
Just released version 1.0.9 with the fix.

**Closed by christav** 2018-01-29 19:06 UTC

**Comment by saraht129** [comment] 2018-01-31 09:38
Hi there, I've updated to 1.0.9 and still getting `Unknown arguments`. My command looks like this:

    appcenter codepush release-react --app {owner}/{appname} --deployment-name Staging --sourcemap-output index.android.bundle.map --output-dir ./android/assets -m

**Comment by svekl** [comment] 2018-02-02 14:09
Hi @saraht129, thanks for report! Reproduced your issue and provided a fix in #379.
