### ISSUE TITLE
Releasing directly to Android store Production suddenly doesn't work anymore

### ISSUE THREAD

**Issue by devedse** [microsoft/appcenter-cli#592] opened 2019-05-30 18:13 UTC
Hi all,

In december last year I fully automated the release of my Android application to the App Store using AppCenter. See for example this build:
https://ci.appveyor.com/project/devedse/deveblockstacker/builds/21288368

However when I just triggered a new build it failed with the error:
`Error: Could not find group Production`

I'm now trying to investigate what is going on, I tried executing the following command locally:
```
appcenter distribute release -g Production -f "C:\XKanWeg\Block\deveblockstacker_android.deveblockstacker_android-Signed (1).apk" -a Devedse/DeveBlockStacker.Android -r "This is a test" --token ****************
```

However this now also returns the error:
`Error: Could not find group Production`

![image](https://user-images.githubusercontent.com/2350015/58654034-53819b00-8317-11e9-9b33-d4f41470025c.png)

Does anyone have an idea on how to fix this?

```
C:\XKanWeg\Block>appcenter distribute release -g Production -f "C:\XKanWeg\Block\deveblockstacker_android.deveblockstacker_android-Signed (1).apk" -a Devedse/DeveBlockStacker.Android -r "This is a test" --token ******************************** --debug
Using appcenter-cli version: 1.1.18
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/distribution_groups/Production/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
/ Loading prerequisites...Response status code: 404
Body: {"error":{"code":"NotFound","message":"Could not find distribution group Production in this app"}}
| Creating release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/release_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
| Creating release upload...Response status code: 201
Body: {"upload_id":"********************************","upload_url":"https://rink.hockeyapp.net/api/sonoma/apps/********************************/app_versions/upload?upload_id=********************************"}
| Finishing release upload...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/release_uploads/********************************",
  "method": "PATCH",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": "{\"status\":\"committed\"}"
}
- Finishing release upload...Response status code: 200
Body: {"release_id":"44","release_url":"v0.1/apps/Devedse/DeveBlockStacker.Android/releases/44"}
| Updating release details...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/releases/44",
  "method": "PUT",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": "{\"release_notes\":\"This is a test\"}"
}
- Updating release details...Response status code: 200
Body: {"release_notes":"This is a test"}
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/Devedse/DeveBlockStacker.Android/distribution_groups/Production",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.18 NodeJS/v12.3.1 win32/10.0.17134",
    "x-api-token": "********************************"
  },
  "body": null
}
Response status code: 404
Body: {"error":{"code":"NotFound","message":"Could not find distribution group with name Production"}}
Error: Could not find group Production
```

**Comment by jphenow** [comment] 2019-06-05 13:47
Hi! I'm from the AppCenter Engineering team. Could you:

* Go to https://appcenter.ms
* Locate your app
* Go to `Distribute`
* Check that the group name you're using for CLI exactly matches the group name we have on AppCenter

If you continue to experience issues, please reach out to our support team by clicking the blue chat icon in the bottom right of the AppCenter website so we can better help you with your issue.

**Comment by devedse** [comment] 2019-06-11 08:48
Well the thing is, is that previously I could release to the group Production. This would then directly put the package on the Android store. As you can see I don't have a Production group here:

![image](https://user-images.githubusercontent.com/2350015/59257408-2d70ca80-8c36-11e9-91d5-6433215b0fac.png)

However when you go to stores, you'll see the Production store:
![image](https://user-images.githubusercontent.com/2350015/59257438-3eb9d700-8c36-11e9-89de-41d954aef98d.png)


To me it sounds very logical that I would want to release directly to the Android store from my build pipeline so I don't get why this functionality doesn't work anymore.

**Comment by devedse** [comment] 2019-06-11 08:51
@jphenow , I also submitted an issue at the AppCenter github:

![image](https://user-images.githubusercontent.com/2350015/59257657-a5d78b80-8c36-11e9-8716-1fc1294702e6.png)

It does seem however that this is not tracked by anyone as I haven't had any response in 12 days 🙄 .

I can't find a "Blue chat icon" though. Would you mind pointing out where it should be?

**Comment by N7K4** [comment] 2019-07-22 12:31
I fight also with the "release to store" function from appcenter-cli. Version 1.2.0.

The appslug `org/product` should be replaced with your values.

With this command
`appcenter distribute releases show --app org/product -r 2`
I was able to see the details about my release:

`
Destinations:         [
                               {
                               "name": "nobody",
                               "id": "xxxxxxxxxxxxxxxxxxxxxxxx",
                               "destinationType": "group"
                               },
                               {
                               "type": "googleplay",
                               "publishingStatus": "submitted",
                               "name": "Beta",
                               "id": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
                               "destinationType": "store"
                               }
                               ]
`

So I expect that the destination type support "group, tester and **STORE**", but when I try
`
appcenter distribute releases add-destination -r 2 -t store -d Beta --app org/product 
`
I got 
`
Error: store is not a valid destination type. Available types are: group, tester
`

Will the value "store" a available parameter for destinationtype in future?

**Comment by phillipleblanc** [comment] 2019-09-03 04:48
@N7K4 @devedse We will be working on adding the ability to distribute to Store destinations via the CLI soon.

**Comment by devedse** [comment] 2019-09-08 17:40
@phillipleblanc , that's great :), keep us posted.

**Comment by devedse** [comment] 2019-09-30 08:58
@jpeg-ms , thanks for fixing this. I saw the documentation is not updated yet. Is this still something on your backlog?

Any idea when this will be released?

**Comment by jpeg-ms** [comment] 2019-10-01 02:19
We will work on the doc. As for the CLI itself, expect a new release today or tomorrow.

**Comment by phillipleblanc** [comment] 2019-10-01 13:47
@devedse - This is now released with version 2.2.0

**Comment by devedse** [comment] 2019-10-01 18:02
@jpeg-ms @phillipleblanc 
When I try to use the list command without logging in but with providing a token I get the following message:
![image](https://user-images.githubusercontent.com/2350015/65987549-55ef2f80-e486-11e9-85ee-ac6750eb34b5.png)

**Comment by devedse** [comment] 2019-10-01 18:29
I did some testing of the actual releasing and that seems to work now, great!

https://ci.appveyor.com/project/devedse/deveblockstacker/builds/27803750

**Comment by jerietve** [comment] 2019-10-02 02:23
Hi @devedse. I'm glad things worked out in the end. I tried to reproduce the error you got, but was unable to. I assume you called `appcenter apps set-current` before, or have the app stored in the environment variable? If not, then you should specify the `--app` flag when calling `distribute stores list`. But in that case you should get an error saying you have to specify the app, instead of what you are seeing. Could you share the order of the commands you executed?

**Comment by devedse** [comment] 2019-10-02 10:25
@jerietve 

I basically did a clean install of appcenter. (Uninstalled the old one and installed the new one).

After that I ran the command I showed (so no login / selecting an app).

Once I did Login though I did get a normal error message that there's no default app selected.

**Comment by jerietve** [comment] 2019-10-04 03:14
Thank you for your reply. I tried a bit more with a clean-ish install (latest version, empty profile, no app set) but can still not reproduce this issue.

You now know what the problem was (must specify app to list stores) and have been able to continue work. We have added official support for publishing to stores, which is what this issue was about. I will close this issue now. Thanks everyone.

**Closed by jerietve** 2019-10-04 03:14 UTC
Labels: Distribute, feature-request
