### ISSUE TITLE
Feature Request: Support for managing Teams in App Center CLI

### ISSUE THREAD

**Issue by jayro4ever** [microsoft/appcenter-cli#1923] opened 2022-04-11 22:50 UTC
It will be very helpful for us to manage Teams in the same way we do Distribution Groups in the App Center CLI. Any info on when that will be available? Thanks!

**Comment by DmitriyKirakosyan** [comment] 2022-08-16 11:49
I'm closing this as a duplicate of https://github.com/microsoft/appcenter-cli/issues/503

**Closed by DmitriyKirakosyan** 2022-08-16 11:49 UTC
Labels: feature request
