### ISSUE TITLE
I cannot run any command

### ISSUE THREAD

**Issue by ahryne** [Microsoft/appcenter-cli#527] opened 2019-01-17 08:46 UTC
I using windows 10, with nvm for windows. (node 8.15.0 / 10.15.0)
If i run related command with my account, returned error.

~~~
appcenter apps list
| Getting app list ...events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:304:10)
    at DestroyableTransform.Writable.write (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:332:62)
    at Pumpify.ondata (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:531:20)
    at emitOne (events.js:116:13)
    at Pumpify.emit (events.js:211:7)
    at readableAddChunk (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:198:18)
    at Pumpify.Readable.push (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:157:10)
    at Pumpify.Duplexify._forward (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\duplexify\index.js:170:26)
    at WinCredStoreParsingStream.onreadable (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\duplexify\index.js:134:10)
    at emitNone (events.js:106:13)
~~~

~~~
appcenter login
| Logging out current user...events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:304:10)
    at DestroyableTransform.Writable.write (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:332:62)
    at Pumpify.ondata (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:531:20)
    at emitOne (events.js:116:13)
    at Pumpify.emit (events.js:211:7)
    at readableAddChunk (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:198:18)
    at Pumpify.Readable.push (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\readable-stream\lib\_stream_readable.js:157:10)
    at Pumpify.Duplexify._forward (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\duplexify\index.js:170:26)
    at WinCredStoreParsingStream.onreadable (C:\Users\seonguk.cho\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\duplexify\index.js:134:10)
    at emitNone (events.js:106:13)

~~~

How can i do?

**Comment by AndreyMitsyk** [comment] 2019-01-17 09:41
Hi @ahryne . Do you have latest appcenter cli version? If not, try to update it.

**Comment by ahryne** [comment] 2019-01-17 09:45
yeah, i uninstalled cli, and clean npm cache (removed diretory), install latest, same error returned.

So i install to another pc, and signed in using my account... same issue occured.

**Comment by AndreyMitsyk** [comment] 2019-01-17 09:54
Mhm. What about previous version? I see some changes in latest version about Duplexify dependency. It may be a reason on node 8.
`npm install -g appcenter-cli@1.1.9`

**Comment by ahryne** [comment] 2019-01-17 10:02
Oh, working well now. Thanks, @AndreyMitsyk!
I tried in node v11.6.0.

**Comment by AndreyMitsyk** [comment] 2019-01-17 10:08
@owenniblock could you please tag this like a bug? Looks like latest cli version is affected. I can try to investigate this and try to fix this today/on the weekend.
The issue _might_ be here: https://github.com/Microsoft/appcenter-cli/pull/512

**Comment by andreialecu** [comment] 2019-01-17 11:40
Confirmed that I'm having the same problem on `1.1.10`. Cannot even `logout`. I believe the version should be pulled from npm.

1.1.9 works properly

**Comment by AndreyMitsyk** [comment] 2019-01-17 18:12
Yep. I can confirm same issue for me with node 10.15.0, win 10, cli 1.1.10.

**Comment by AndreyMitsyk** [comment] 2019-01-17 20:49
I managed to find a root cause and fix this issue: https://github.com/Microsoft/appcenter-cli/pull/528
Locally, everything looks ok with this fix. Code review from MS employees needed + new release, because current version is totally broken for Windows.

**Comment by owenniblock** [comment] 2019-01-21 10:34
Thanks all - I'll get this released today. @AndreyMitsyk - thanks for the digging and PR!

**Comment by owenniblock** [comment] 2019-01-21 10:59
Please update to v1.1.11 (you may have to wait for npm caches to clear before it appears for you).

https://github.com/Microsoft/appcenter-cli/releases/tag/v1.1.11

I'll close this but keep an eye - if this doesn't solve it for all of you please comment here and I'll reopen and investigate.

CC @amchew

**Closed by owenniblock** 2019-01-21 10:59 UTC

**Comment by amchew** [comment] 2019-01-22 22:53
Thanks @owenniblock! Hi @ahryne, @andreialecu and @AndreyMitsyk thanks for bearing with us! Could you update to CLI v1.1.11, and see if this problem still persists for you? It should be fixed now.
