### ISSUE TITLE
Issue with appcenter-cli 2.10.8 where it now requires login token and prior versions did not

### ISSUE THREAD

**Issue by biozal** [microsoft/appcenter-cli#1832] opened 2022-02-08 17:14 UTC
### **Description**
In version 2.10.8 when using the cli tool in a github action I would run the following command to tell it to run a test:

appcenter test run espresso --token "${{secrets.APPCENTER_QUERY_API_KEY}}" --app "Couchbase-Inc./UserProfile-Query-Android" --devices cbc1464e --app-path "src/app/build/outputs/apk/debug/app-debug-signed.apk" --test-series "userprofile-query" --locale "en_US" --build-dir "src/app/build/outputs/apk/androidTest/debug" 

secrets.APPCENTER_QUERY_API_KEY comes from the App Center web portal under Settings -> App API Tokens -> New API Token.  Now get the error:

Error: Command 'appcenter test run espresso' requires a logged in user. Use the 'appcenter login' command to log in.

This acts like a local user needs to be logged in, instead of using an API key.  I don't want to use a user-generated token because if people leave the company this will break.  Using an API key is the proper way to support this. 

### **Repro Steps**
Please list the steps used to reproduce your issue.
1.  See description for details.

### **Expected behavior**
I expected API keys to work like they did in 2.10.7, but instead they do not work in 2.10.8 and instead throw an error when trying to run espresso tests.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
See description

2. Which version of the App Center CLI are you using?
2.10.8

3. Which OS version did you experience the issue on?
    Ubuntu 20.04.1 LTS

4. What command line/shell are you using?
bash

5. What version of Node.js and NPM/Yarn are you using?

/opt/hostedtoolcache/node/14.1[8](https://github.com/couchbase-examples/android-java-cblite-userprofile-query/runs/5112977494?check_suite_focus=true#step:3:8).3/x64/bin/node --version
v14.18.3

/opt/hostedtoolcache/node/14.18.3/x64/bin/npm --version
6.14.15

6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:

This is a CI/CD Pipeline would need more details on how to capture this in a github action.

**Comment by AnatolyPristensky** [comment] 2022-02-09 12:45
Hello @biozal, 
Thank you for getting in touch with us! 
We are looking into your issue and will update this conversation once get results.

**Comment by IlyaBausovAkvelon** [comment] 2022-05-09 22:38
Hello @biozal,
Could you run this command from your machine? Does it work from your machine? If there are the same result as on Github Actions could you run this command with debug option?

**Comment by IlyaBausovAkvelon** [comment] 2022-05-13 00:31
@biozal is this issue still appearing?

**Comment by IlyaBausovAkvelon** [comment] 2022-05-19 22:55
@biozal does the issue is still actual?

**Comment by IlyaBausovAkvelon** [comment] 2022-05-27 00:17
@biozal we are closing this issue for now since we cannot reproduce it.
Please feel free to re-open this if you're still facing this problem.

**Comment by badereddineqodia** [comment] 2022-05-30 11:19
Visit https://appcenter.ms/cli-login?hostname={your hostname} and enter the code:
after the brower will generate an access code, copy it then run this command
echo {access code genrate by your browser } | appcenter login --token $APPCENTER_API_TOKEN

**Closed** 2022-08-09 07:57 UTC
