### ISSUE TITLE
Flag to disable parallel uploads introduced in version 2.6.0

### ISSUE THREAD

**Issue by aaratn** [microsoft/appcenter-cli#953] opened 2020-06-22 12:18 UTC
We are using travis-ci and suddenly our distribute command stopped working until we found out that there is a new concurrent upload feature introduced in version 2.6.0. To fix this issue we downgraded the version to previous one i.e 2.5.4.

We are looking for an option where we can disable con-currency for distribution release.

**Comment by andysousa** [comment] 2020-06-23 01:00
same here, i could not get an upload to work for the life of me behind a corporate proxy with the 2.6.0 release, had to go back to 2.5.4.  I am not sure what changed... but its either not honoring the proxy correctly or something else.

**Comment by Jamminroot** [comment] 2020-07-07 13:36
Hey, @aaratn, @andysousa, thanks for getting in touch. 
I've tried to repro the problem with my own repo (travis-CI with private repo), and it did not quite reproduce, and release was correctly created. Is there anything else I can be missing? Have a look at configs I made to test (apk uploaded as binary):
```yml
language: node_js
node_js:
  - node
script:
  - bash scripts/deploy.sh
```
```bash
#!/bin/bash
npm install -g appcenter-cli
appcenter login --token $TOKEN --debug true
appcenter distribute release -f test.apk -r "Travis-CI Distribution via appcenter-cli" --app $APP_NAME --group Public --debug true
```
Also, can you run appcenter-cli with debug logging turned on? Just append `--debug true` to the command. Don't forget to omit sensitive information (secrets, tokens, etc).
Sorry for such a delay in response.

**Comment by aaratn** [comment] 2020-07-07 17:00
@Jamminroot 

Can you try doing same for ios? I was testing this for ios builds

**Comment by andysousa** [comment] 2020-07-07 17:09
this happens behind a corporate proxy for me... i will get you the debug output in a little bit

**Comment by Jamminroot** [comment] 2020-07-07 19:53
@andysousa, sure, waiting for those.
@aaratn did test that - also no problems.
@andysousa, @aaratn Need more context for further investigation. So far it looks more like a problem with the related changes we made recently... Can you guys provide me the exact command (with args) you are running? And again - don't forget to edit sensitive info out before posting here.

**Comment by Jamminroot** [comment] 2020-07-09 07:11
@andysousa @aaratn can you check that specifying token explicitly as a command line argument rather than env var helps?
[This PR](https://github.com/microsoft/appcenter-cli/pull/979) fixes recent bug with getting token from env - that would explain why travis-ci worked for me.

**Comment by andysousa** [comment] 2020-07-09 13:02
@Jamminroot I just realized I probably highjacked this issue with another one, but maybe its related.  Let me know and I can move this to a new issue. 

At any rate, I finally got around to getting the debug info for you.  Again, 2.6 fails every time and 2.5 is fine.  We are behind a corporate proxy which i believe is the issue.  I use the command line for token, as you can see.. not the env var.

```
ENGOSXBuild:Mobile Apps buildserver$ npx appcenter login --token <token> --quiet --disable-telemetry && npx appcenter distribute release -f blahblah*.ipa --app blahblah-Inc/blahblah-Mobile-iOS-Dev -g blahblah\ Mobile --debug true
Logged in as AndySousa
Using appcenter-cli version: 2.6.1
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/blahblah-Inc/ blahblah-Mobile-iOS-Dev/distribution_groups/blahblah%20Mobile/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.6.1 NodeJS/v13.9.0 darwin/18.7.0",
    "x-api-token": "<token>",
    "internal-request-source": "cli",
    "diagnostic-context": "not sure what that was, but removing it just in case",
    "cli-command-name": "distribute release"
  },
  "body": null,
  "strictSSL": false,
  "agent": {
    "options": {
      "proxy": {
        "host": "<proxy ip>",
        "port": "80",
        "protocol": "http:"
      }
    },
    "proxyOptions": {
      "host": "<proxy ip>",
      "port": "80",
      "protocol": "http:"
    },
    "maxSockets": null,
    "requests": [],
    "sockets": [],
    "_events": {},
    "_eventsCount": 1
  }
}
/ Loading prerequisites...Response status code: 404
Body: {"message":"Not found. Correlation ID: eb4d4843-32fe-4660-b73d-368d5168de09","statusCode":404,"code":"Not Found"}
Command Failure at FetchError: request to https://api.appcenter.ms/v0.1/apps/blahblah-Inc/blahblah-Mobile-iOS-Dev/uploads/releases failed, reason: connect ETIMEDOUT 52.138.116.79:443
    at ClientRequest.<anonymous> (/Users/buildserver/tfsmacagent/_work/r3/a/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Command 'distribute release -f blahblah.ipa --app blahblah-Inc/blahblah-Mobile-iOS-Dev -g blahblah Mobile --debug true' failed with exception "request to https://api.appcenter.ms/v0.1/apps/blahblah-Inc/blahblah-Mobile-iOS-Dev/uploads/releases failed, reason: connect ETIMEDOUT 52.138.116.79:443"
```

**Comment by Jamminroot** [comment] 2020-07-09 14:40
Thanks for sharing that. I'll discuss that with team and see if I can reproduce it locally (transparent proxy did not repro( )

**Comment by Jamminroot** [comment] 2020-07-13 19:32
Did some testing with non-transparent proxy - still worked fine. Can you check that API endpoints are reachable from the network? @andysousa 
You can see those in [diff](https://github.com/microsoft/appcenter-cli/pull/909/files?file-filters%5B%5D=.md&file-filters%5B%5D=.ts), they have `/uploads/releases` in path.

**Comment by Jamminroot** [comment] 2020-07-16 14:44
A friendly ping, @andysousa - how's CLI doing? Were you able to address my suggestion?

**Comment by andysousa** [comment] 2020-07-16 14:55
I am assuming you mean the url ?
https://api.appcenter.ms/v0.1/apps/blahblah-Inc/blahblah-Mobile-iOS-Dev/uploads/releases

I am getting 400s from it when I do a get or just random... so i would think its reachable

![image](https://user-images.githubusercontent.com/42151009/87686719-d6032f00-c752-11ea-8554-17623b1ae663.png)

**Comment by Jamminroot** [comment] 2020-07-22 07:18
@andysousa I see. What about the app name - we've noticed you have a space in distribution group - is that an edit or do you actually happen to have one?

**Comment by Jamminroot** [comment] 2020-07-22 07:29
In other words: can you check if changing this `-g blahblah\ Mobile ` to `-g 'blahblah Mobile'` helps?

**Comment by andysousa** [comment] 2020-07-23 18:55
so doing it with the ' ', the prerequisutes seemed to have loaded correctly (won't show it here because its filled with names... but then immediately fails after that.

```
Command Failure at FetchError: request to https://api.appcenter.ms/v0.1/apps/blahblah-Inc/blahblah-Mobile-iOS-Dev/uploads/releases failed, reason: connect ETIMEDOUT 52.138.116.79:443
    at ClientRequest.<anonymous> (/Users/buildserver/tfsmacagent/_work/r3/a/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Command 'distribute release -f SensiWatch_Mobile_v0.0.1.ipa -g blahblah Mobile --app blahblah-Inc/blahblah-Mobile-iOS-Dev -R release-notes.md --debug true' failed with exception "request to https://api.appcenter.ms/v0.1/apps/blahblah-Inc/blahblah-Mobile-iOS-Dev/uploads/releases failed, reason: connect ETIMEDOUT 52.138.116.79:443"
ENGOSXBuild:Mobile Apps buildserver$
```

**Comment by Jamminroot** [comment] 2020-07-29 08:57
Again - sorry for such a delay in response.
I see that in the output you provided, there is no quotes around `blahblah Mobile` for `-g` param (group).
Is that edited? Or is it how CLI provides output?

**Comment by andysousa** [comment] 2020-07-29 09:52
@Jamminroot i def put the quotes around the command. That's the output from the cli, could it have stripped it?

**Comment by Jamminroot** [comment] 2020-07-30 07:21
@andysousa, Yeah, I guess CLI "ate" those quotes on the output.

**Comment by jphenow** [comment] 2020-07-30 14:51
Out of curiosity; could you try this again, but instead of the `login` command, can you add `--token <token>` to the `distribute release` command?

**Comment by Jamminroot** [comment] 2020-08-10 07:19
@jphenow sorry for a delay in response. Can you elaborate on this one - I don't think that `distribute release` is to be used with `login` at all.

**Comment by Jamminroot** [comment] 2020-08-11 08:51
@andysousa @aaratn just a ping here - are you still facing the problem with the CLI?

**Comment by aaratn** [comment] 2020-08-11 08:54
@Jamminroot I didn't try it unless there is a patch / flag to disable parallel uploads. We are using travis-ci and it doesn't support parallel uploads.

**Comment by Px7-941** [comment] 2020-08-11 09:28
Here is a similar ticket. #982 The console output is the same. The problem almost seems to be that the new parallel upload does not set the proxy properly.

**Comment by Jamminroot** [comment] 2020-08-11 15:51
@andysousa can you also check if uploading through the portal work for you, while behind the proxy?

**Comment by andysousa** [comment] 2020-08-11 15:54
@Jamminroot what is the portal?  If you mean the webapp, yeah that works fine.  Also 2.5 of the CLI works fine too.  

@Px7-941 is correct, #982 probably better reflects the issue.  This thread sort of took away from @aaratn 's original problem, although the same cause.

**Comment by Jamminroot** [comment] 2020-08-11 16:16
@andysousa @aaratn is the problem still present in v. 2.6.5 recently released?

@andysousa since #982 describes your problem better than initial issue here, lets continue discussion there (I'll attach new thread to our board item so that it's not lost). We'll do additional testing on our side - upload through portal should use same requests as upload through CLI - this is why it's odd that CLI upload is not working as intended, while portal does.

@aaratn As for the initial feature request (flag to disable parallel uploads) - I'm turning this issue to a feature request, but unfortunately that is not something we are going to implement in near future.

**Comment by simonesabella** [comment] 2020-08-12 16:04
> @andysousa @aaratn is the problem still present in v. 2.6.5 recently released?
> 
> @andysousa since #982 describes your problem better than initial issue here, lets continue discussion there (I'll attach new thread to our board item so that it's not lost). We'll do additional testing on our side - upload through portal should use same requests as upload through CLI - this is why it's odd that CLI upload is not working as intended, while portal does.
> 
> @aaratn As for the initial feature request (flag to disable parallel uploads) - I'm turning this issue to a feature request, but unfortunately that is not something we are going to implement in near future.

How can I disable the parallel upload flag on 2.6.5?

**Comment by russelarms** [comment] 2021-01-28 13:39
I'm closing this as the previous uploading API has been deprecated and will be unavailable soon.

**Closed by russelarms** 2021-01-28 13:39 UTC
Labels: Distribute, feature-request
