### ISSUE TITLE
Proxy support for codepush release

### ISSUE THREAD

**Issue by swbradsh** [microsoft/appcenter-cli#682] opened 2019-10-16 15:53 UTC
I'm not able to do a release when running behind an http proxy.  Most simple appcenter queries will work fine, but when it comes to submitting a code release, this will fail.

When I run a similar command as below, it always fails.
`appcenter codepush release -a appname -t 1.0.0 -d Staging -c ./platforms/android/app/src/main/assets/www --debug`

The output ends with the following:

> Uploading bundle...Response status code: 200
> Body: {"id":"92131e27-9845-4acd-ad77-e1dadf7055a2","upload_domain":"https://file.appcenter.ms","token":"?sv=REDACTED"}
> [14:31:03.495]: Setting state: New (0)
> [14:31:03.498]: Upload Initialized
> [14:31:03.502]: Setting metadata for AssetId:  92131e27-9845-4acd-ad77-e1dadf7055a2
> [14:31:03.504]: File name: 6SF1iHNdwDGf63t.zip
> [14:31:03.511]: File size: 2661583
> [14:31:03.523]: CorrelationId: 92131e27-9845-4acd-ad77-e1dadf7055a2
> in sendRequest
> - Uploading bundle...[14:31:03.704]: Set metadata failed: AssetId: 92131e27-9845-4acd-ad77-e1dadf7055a2, StatusCode: none, errorMessage: undefined
> [14:31:03.708]: Setting state: FatalError (500)
> Error: Error: The asset cannot be uploaded. Try creating a new one
> 

I've traced this to  `appcenter-file-upload-client` module which is using the `superagent` HTTP request library. However, there is no proxy support here. I found that if I manually include and configure the optional add-on [superagent-proxy](https://github.com/TooTallNate/superagent-proxy) inside the request.js file, I can get this to work.

I couldn't find appcenter-file-upload-client in Github, but this should be a rather simple change.  Right now, I don't see how this library can be used in a corporate/enterprise environment.

**Comment by ahbilal-ms** [comment] 2019-10-30 23:34
@swbradsh Thanks for sending over the details. We are looking into it and will update you shortly. Thanks

**Comment by ahbilal-ms** [comment] 2019-10-31 00:40
@swbradsh We are investigating the issue and have few questions for you:

**Comment by swbradsh** [comment] 2019-10-31 01:29
@ahbilal-ms 
1. This is a new app - no migration.
2. This is my first time using this tool. If I drop off my corporate network, and goto my home wifi, everything works fine.

**Comment by ahbilal-ms** [comment] 2019-10-31 01:37
@swbradsh Thanks! It definitely seems to be an issue with the proxy, which we don't support at this time with our cli offering. Few of our customer have temporarily fixed this issue by enabling whitelist for the following addresses: https://intercom.help/appcenter/en/articles/1881230-urls-and-ip-addresses-to-whitelist-for-app-center 

Also, I am working with the team to recommend a feature to fix this issue. I can't comment on the timeline but will come back to you with more updates. Thanks

**Comment by swbradsh** [comment] 2020-01-08 14:51
If anyone wants a work-around for this issue, here is how i solved it.
Install superagent-proxy globally.
`npm i -g superagent-proxy`

Navigate to your installed appcenter-cli module and edit the `request.js` file. For me, I found the file here: `C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\appcenter-file-upload-client\dist\core\request.js`

You're adding 2 lines to this file. See below.

```
....
var request = require("superagent");
require('superagent-proxy')(request);    <------- add this line
function sendRequest(requestOptions, log) {
    var abort = 0;    
    var req = request
        .post(requestOptions.url)
        .proxy(process.env.http_proxy)   <------ add this line
....

```

Make sure your http_proxy is set in your environment variable, and it should work now.  Note, that if you update the appcenter-cli, you might have to make this change again.

**Comment by michaelgmcd** [comment] 2020-04-07 20:12
My team has been using appcenter@1.1.19 and it has been working fine with our proxy settings. I'm not sure when this was broken.

**Comment by EhsanSarshar** [comment] 2020-10-10 16:22
I am not behind a proxy but still have the issue

**Comment by aurelN** [comment] 2020-12-09 20:33
how exactly to i set https_proxy?
I'm on MAC and edited the .bach_profile file by adding 
`export https_proxy=myProxy
export http_proxy=myProxy`

and now I'm getting `failed with exception "Cannot read property 'toLowerCase' of null"`

**Comment by harshlakhanpal** [comment] 2021-02-04 11:51
found a simple hack which works 90% of the times,
simply switch the network/wifi you're connected to and the run the command.

**Comment by frank505** [comment] 2021-09-15 01:36
it strange that @harshlakhanpal answer worked for me so strange

**Comment by puneetkansal04** [comment] 2021-11-09 11:43
Hey I am getting the same issue, Checked with changing and restarting network. Not able to get how to resolve in Mac. I was working fine before 1 week.

**Comment by namlh19** [comment] 2021-11-09 11:44
> Hey I am getting the same issue, Checked with changing and restarting network. Not able to get how to resolve in Mac. I was working fine before 1 week.

It still work fine at noon. But now i get same issue with you.

**Comment by aurelN** [comment] 2021-11-09 11:46
https://status.appcenter.ms/
![image](https://user-images.githubusercontent.com/15376655/140918517-c49ef88d-7112-469d-8547-eb04a010830c.png)

**Comment by heytulsiprasad** [comment] 2021-11-09 11:46
Woah is this a recurring issue? Happening for me too. Among the things I've tried are:
1. npm install -g appcenter-cli@2.5.4 [Link](https://github.com/microsoft/react-native-code-push/issues/1680#issuecomment-826110941)
2. @swbradsh's comment on using superagent-proxy [above](https://github.com/microsoft/appcenter-cli/issues/682#issuecomment-572103918)
3. Changing my network

I've been banging my head since past 2 hours, any some help would be appreciated. 👍

**Comment by puneetkansal04** [comment] 2021-11-09 11:50
@aurelN Thanks may be I will work. Let's wait for sometime and then will try again if it will work.

@heytulsiprasad @namlh19 you can wait as @aurelN mentioned a updated may be it will resolve it. Update here once anybody get a solution.

**Comment by aurelN** [comment] 2021-11-09 11:51
@puneetkansal04 Based on the info on the site you also need to update your local cli to the latest version in order to use the new endpoint.
"Update - upload.appcenter.ms url has been discontinued - please use file.appcenter.ms instead.

Please update appcenter-cli, Jenkins and Fastlane plugins and App Center ADO Distribute task to the latest version if you have issues with distribution."

But first wait for the maintenance to finish.

**Comment by dn32** [comment] 2021-11-09 11:56
> https://status.appcenter.ms/ ![imagem](https://user-images.githubusercontent.com/15376655/140918517-c49ef88d-7112-469d-8547-eb04a010830c.png)

This is the problem. Server down. Perhaps when Microsoft starts using AWS it will normalize its operations.

**Comment by kyle-ssg** [comment] 2021-11-09 12:18
Yep, further to above we've been getting this using the latest cli in CICD (appcenter-cli@2.10.4).

**Comment by tarikdem** [comment] 2021-11-09 13:10
The same issue happening in an Azure DevOps pipeline (`macOS-11` with `appcenter-cli@2.10.4`) when running `appcenter distribute release`.

**Comment by puneetkansal04** [comment] 2021-11-10 07:17
ok now its working fine

**Comment by mrvincenzo** [comment] 2023-05-21 13:27
> If anyone wants a work-around for this issue, here is how i solved it. Install superagent-proxy globally. `npm i -g superagent-proxy`
> 
> Navigate to your installed appcenter-cli module and edit the `request.js` file. For me, I found the file here: `C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\appcenter-file-upload-client\dist\core\request.js`
> 
> You're adding 2 lines to this file. See below.
> 
> ```
> ....
> var request = require("superagent");
> require('superagent-proxy')(request);    <------- add this line
> function sendRequest(requestOptions, log) {
>     var abort = 0;    
>     var req = request
>         .post(requestOptions.url)
>         .proxy(process.env.http_proxy)   <------ add this line
> ....
> ```
> 
> Make sure your http_proxy is set in your environment variable, and it should work now. Note, that if you update the appcenter-cli, you might have to make this change again.

For `appcenter-file-upload-client@0.1.0`, the change is in `node_modules/appcenter-file-upload-client/dist/core/request.js`

```
...
var request = require("superagent");
require('superagent-proxy')(request); // <--

function sendRequest(requestOptions, log) {
    var abort = 0;
    var req = request(requestOptions.method, requestOptions.url)
        .set('X-XblCorrelationId', requestOptions.correlationId)
        .set('MS-CV', requestOptions.correlationVector);

    if (process.env.http_proxy) { // <--
        req.proxy(process.env.http_proxy)
    }
    ...
```

םר

**Comment by DmitriyKirakosyan** [comment] 2023-09-25 11:11
I'm closing this issue. Please let me know if anyone is still facing it.

**Closed by DmitriyKirakosyan** 2023-09-25 11:11 UTC
Labels: CodePush, Enhancements

**Comment by mrvincenzo** [comment] 2023-10-26 07:31
@DmitriyKirakosyan the issue is still reproducible. proxy settings are not honored by app-center-upload-client@0.1.0

**Comment by DmitriyKirakosyan** [comment] 2023-11-09 07:29
@mrvincenzo , I just tested uploading release with a proxy and it worked well for me.

Make sure you are using the latest `appcenter-cli` (2.14.0). The `appcenter-file-upload-client-node` current version is `1.2.11`.

**Comment by mrvincenzo** [comment] 2023-11-09 12:07
@DmitriyKirakosyan The code I referenced, [appcenter codepush release](https://github.com/microsoft/appcenter-cli/blob/9930a9d5171a780290c99f617a651d13023ed3e6/src/commands/codepush/lib/codepush-release-command-base.ts#L195C1-L195C1), doesn't use `appcenter-file-upload-client-node`. Instead it uses, [appcenter-file-upload-client](https://github.com/microsoft/appcenter-cli/blob/master/package.json#L114C1-L114C1), which means that the problem is still there

**Comment by DmitriyKirakosyan** [comment] 2023-11-16 05:48
@mrvincenzo , you are right. I'm sorry for the confusion. `appcenter-file-upload-client` doesn't support proxy at this moment.

**Comment by mrvincenzo** [comment] 2023-11-16 09:50
@DmitriyKirakosyan ok, now that we are aligned, IMHO there 2 possible fixes
1. Update `appcenter-file-upload-client` package to support proxy
2. Patch `appcenter-file-upload-client` with `patch-package` in `appcenter-cli`

The fix is as simple as:  https://github.com/microsoft/appcenter-cli/issues/682#issuecomment-1556180535

**Comment by Solid-Metal** [comment] 2024-09-18 02:14
> found a simple hack which works 90% of the times, simply switch the network/wifi you're connected to and then run the command.

works like a charm lol
