### ISSUE TITLE
distribute release, 403, invalid token, ValidationFailure

### ISSUE THREAD

**Issue by jolen10** [microsoft/appcenter-cli#1337] opened 2021-03-16 23:47 UTC
### **Description**
I'm getting a 403 invalid token (ValidationFailure) on distribute release.
I think it could be because I'm using my personal token but I'm distributing a project from a team I'm included as an admin.
Manually uploading it also reports invalid token but it does got uploaded and I was able to distribute it manually.

### **Repro Steps**
distribute release on a project owned by a team you're included using your personal token
`appcenter login --token <your_personal_token>`
`appcenter distribute release --debug --app <team>/<project> --file <binary_file> --group <group_name>`

### **Expected behavior**
My build will get uploaded and distributed to selected group

### **Details**
version 2.7.4
macOS BigSur 11.2.3
/bin/bash
node v15.0.1, npm 7.0.3

### **Logs**
```
$ appcenter distribute release --debug --app alfred-at-mint-10b6/CVFR-mPOS-UAT --file "CVFR-mPos-Uat-1.0.0 (1).ipa" --group "Ian"
Using appcenter-cli version: 2.7.4
| Loading prerequisites...logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/alfred-at-mint-10b6/CVFR-mPOS-UAT/distribution_groups/Ian/members",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.7.4 NodeJS/v15.0.1 darwin/20.3.0",
    "x-api-token": "08b9bbe7c02a6bada22eb2320f41b5d5d736f54d"
  },
  "body": null
}
\ Loading prerequisites...Response status code: 200
Body: [{"id":"42fc4413-7f58-4f09-8551-4e40786fd330","display_name":"Ian Lopez","email":"ian.lopez@mintpayments.com","name":"ian.lopez-mintpayments.com","avatar_url":null,"can_change_password":false,"created_at":"2021-03-01T01:45:01.000Z","origin":"appcenter"}]
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/alfred-at-mint-10b6/CVFR-mPOS-UAT/distribution_groups/Ian",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.7.4 NodeJS/v15.0.1 darwin/20.3.0",
    "x-api-token": "08b9bbe7c02a6bada22eb2320f41b5d5d736f54d"
  },
  "body": null
}
Response status code: 200
Body: {"id":"6b328015-1faf-459d-8af6-d3c5b2c24da9","name":"Ian","origin":"appcenter","display_name":"Ian","is_public":false}
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/alfred-at-mint-10b6/CVFR-mPOS-UAT/releases/3/groups",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/2.7.4 NodeJS/v15.0.1 darwin/20.3.0",
    "x-api-token": "08b9bbe7c02a6bada22eb2320f41b5d5d736f54d"
  },
  "body": "{\"id\":\"6b328015-1faf-459d-8af6-d3c5b2c24da9\",\"mandatory_update\":false,\"notify_testers\":true}"
}
Response status code: 403
Body: {"message":"invalid token","code":"ValidationFailure","statusCode":403}
Command Failure at Error: invalid token
    at /Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/dist/util/apis/generated/operations/releasesOperations.js:1791:19
    at retryCallback (/Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (/Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at /Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/rpRegistrationFilter.js:59:14
    at handleRedirect (/Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:39:9)
    at /Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/formDataFilter.js:23:14
    at /Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/filters/logFilter.js:21:14
    at Request._callback (/Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/ms-rest/lib/requestPipeline.js:125:16)
    at Request.self.callback (/Users/ian/.nvm/versions/node/v15.0.1/lib/node_modules/appcenter-cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:327:20)
Error: Command 'distribute release --debug --app alfred-at-mint-10b6/CVFR-mPOS-UAT --file CVFR-mPos-Uat-1.0.0 (1).ipa --group Ian' failed with exception "invalid token"
```

**Comment by russelarms** [comment] 2021-03-17 08:09
Hi @jolen10! It is most probably a duplicate of https://github.com/microsoft/appcenter-cli/issues/1332
Feel free to reply if the issue is not resolved for you.

**Closed by russelarms** 2021-03-17 08:09 UTC
