### ISSUE TITLE
Invite a member in a team via AppCenter-Cli

### ISSUE THREAD

**Issue by nehasonakul777** [microsoft/appcenter-cli#2061] opened 2022-08-14 15:32 UTC
**Is your feature request related to a problem? Please describe.**
Add a CLI command that invites a members to a Team ( as we can invite a collaborator in an org )

**Describe the solution you'd like**
The CLI acts just like the web does.

**Describe alternatives you've considered**
Not Any

**Additional context**
Since you invite a collaborator in an organisation via Appcenter CLI command , similarly please provide command to invite  members in a particular team.

**Comment by aleksandr-dorofeev** [comment] 2022-08-15 14:06
Hey @nehasonakul777 
This looks like a duplicate of #1847.
Therefore, I close this issue, feel free to reopen if you think otherwise or if there are additional questions.

**Closed by aleksandr-dorofeev** 2022-08-15 14:06 UTC
Labels: feature-request

**Comment by nehasonakul777** [comment] 2022-08-16 07:44
Hi @aleksandr-dorofeev 
Issue #1847 is related to distribution groups.
I’m looking for inviting a user to team.
Can u please provide a command for the same. 
Thanks.

**Comment by DmitriyKirakosyan** [comment] 2022-08-16 11:50
Hi @nehasonakul777 , sorry for the confusion. The correct link of the duplicate is this: https://github.com/microsoft/appcenter-cli/issues/503.

**Comment by nehasonakul777** [comment] 2022-08-16 12:11
Hi @DmitriyKirakosyan 
Thank you for the support from your end. Hope you are doing well !

#503 mentions about the solution to add the apps to a team.
I’m looking for the Appcenter CLI command to add/invite a user to the team.

**Comment by DmitriyKirakosyan** [comment] 2022-08-17 07:37
The 503 issue is about supporting managing Teams in general, also there is another duplicate here #1923.
I understand that you only need to add a user to the team, however when we implement this feature, we will implement all Teams related commands anyway.

Feel free to leave a message in 503, asking your specific needs.
