### ISSUE TITLE
Can't push tests on windows

### ISSUE THREAD

**Issue by rmarinho** [microsoft/appcenter-cli#688] opened 2019-10-31 09:06 UTC
Hi, we are trying to move our CI to use windows machines and we discover that appcenter cli doesn't work on windows.

here's our error code :

```
[command]C:\windows\system32\cmd.exe /D /S /C "C:\xfteam-vs2017-5\_work\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd test prepare uitest --artifacts-dir C:\xfteam-vs2017-5\_work\r2\a\AppCenterTest --app-path C:/xfteam-vs2017-5/_work/r2/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa --build-dir C:\xfteam-vs2017-5\_work\r2\a/build/OSXArtifacts/ios --uitest-tools-dir C:\xfteam-vs2017-5\_work\r2\a/build/OSXArtifacts/testcloud --include-category ViewBaseTests --exclude-category ManualReview --exclude-category --quiet"
2019-10-30T19:06:49.3463385Z Error: Command test prepare uitest --artifacts-dir C:\xfteam-vs2017-5\_work\r2\a\AppCenterTest --app-path C:/xfteam-vs2017-5/_work/r2/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa --build-dir C:\xfteam-vs2017-5\_work\r2\a/build/OSXArtifacts/ios --uitest-tools-dir C:\xfteam-vs2017-5\_work\r2\a/build/OSXArtifacts/testcloud --include-category ViewBaseTests --exclude-category ManualReview --exclude-category --quiet is invalid
2019-10-30T19:06:49.3745463Z ##[error]Error: C:\xfteam-vs2017-5\_work\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd failed with return code: 1
```

**Comment by cocowalla** [comment] 2019-11-05 09:19
This part of your command looks wrong:

`--exclude-category --quiet`

You are missing the category to be exluded.

**Comment by rmarinho** [comment] 2019-11-05 10:42
this work as is on a OSX machine. 

```
2019-11-04T20:57:01.3606300Z [command]/usr/local/bin/appcenter test prepare uitest --artifacts-dir /Users/runner/runners/2.160.0/work/r1/a/AppCenterTest --app-path /Users/runner/runners/2.160.0/work/r1/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa --build-dir /Users/runner/runners/2.160.0/work/r1/a/build/OSXArtifacts/ios --uitest-tools-dir /Users/runner/runners/2.160.0/work/r1/a/build/OSXArtifacts/testcloud --include-category ViewBaseTests --exclude-category ManualReview --exclude-category --quiet
2019-11-04T20:57:16.7369190Z Preparing tests... done.
2019-11-04T20:57:16.7507890Z Tests are ready to run. Manifest file was written to /Users/runner/runners/2.160.0/work/r1/a/AppCenterTest/manifest.json
2019-11-04T20:57:16.7778250Z [command]/usr/local/bin/appcenter test run manifest --manifest-path /Users/runner/runners/2.160.0/work/r1/a/AppCenterTest/manifest.json --app-path /Users/runner/runners/2.160.0/work/r1/a/build/OSXArtifacts/ios/XamarinFormsControlGalleryiOS.ipa --app xtc-Xamarin-Forms/XamControl --devices xtc-Xamarin-Forms/iOS11 --test-series master --async --locale en_US --vsts-id-variable AppCenterTestRunId --quiet --token ***
2019-11-04T20:57:18.2819090Z Preparing tests... done.
2019-11-04T20:57:18.8060350Z Validating arguments... done.
2019-11-04T20:57:19.3930830Z Creating new test run... done.
2019-11-04T20:57:19.5941730Z Validating application file... done.
2019-11-04T20:57:27.3274080Z Uploading files... done.
2019-11-04T20:57:32.4473750Z Starting test run... done.
2019-11-04T20:57:32.4501550Z Accepted devices: 
2019-11-04T20:57:32.4502600Z   - Apple iPhone X (11.4.1)
2019-11-04T20:57:32.4502840Z 
2019-11-04T20:57:32.4531040Z 
2019-11-04T20:57:32.4532590Z Test Report: https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/XamControl/test/series/master/runs/751c2094-d77c-487b-9b92-89e0d82aafcc
2019-11-04T20:57:32.4532960Z 
``

**Comment by rmarinho** [comment] 2019-11-05 10:42
https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=637&_a=release-environment-logs&environmentId=18905

**Comment by cocowalla** [comment] 2019-11-05 10:58
I guess command line parsing works slightly differently on MacOS :man_shrugging:, but `--exclude-category` without a value is obviously not right; I thought it would be worth correcting this and trying.

**Comment by phillipleblanc** [comment] 2019-11-06 07:42
@rmarinho - Did removing that extra parameter fix your issue?

**Comment by Brosten** [comment] 2019-11-09 12:31
I also get the "is invalid" now (from my Azure Devops pipeline). 
The exact same build-step worked yesterday, but not today.

Error: Command test prepare uitest --artifacts-dir d:\a\r1\a\$(Build.ArtifactStagingDirectory)\AppCenterTest --app-path d:/a/r1/a/_MyApp.Android.Main/drop/App/se.my.app.apk --build-dir d:\a\r1\a/_MyApp.Android.Main/drop/Test --uitest-tools-dir d:\a\r1\a/_MyApp.Android.Main/drop/TestTools --quiet is invalid

**Comment by kkuepper** [comment] 2019-11-11 21:40
We're having the same problem. Since Thursday the DevOps build is failing.

**Comment by Brosten** [comment] 2019-11-12 07:43
That is true.  We run on hosted agents in DevOps and changing from Windows to Mac for the agent job running the tests solved the problem. I still Think MS needs to fix the broken runs on Windows hosted agents.

**Comment by QATestGD** [comment] 2019-11-12 09:46
I am experiencing the same issue, I am trying to run Android tests on DevOps.  I am getting the below error message:

[command]C:\windows\system32\cmd.exe /D /S /C "d:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd test prepare uitest --artifacts-dir d:\a\1\a\AppCenterTest --app-path d:/a/1/b/UITest_UAT/com.Dimplex.DimplexControl.apk --build-dir d:\a\1\b/UITest_UAT/test-assembly --uitest-tools-dir d:\a\1\s/DimplexControl/Code/packages/Xamarin.UITest.2.2.7/tools --include-category Schedules --include-category ServiceEngineer --include-category UserManagement --include-category ZoneManagement --quiet"
Error: Command test prepare uitest --artifacts-dir d:\a\1\a\AppCenterTest --app-path d:/a/1/b/UITest_UAT/com.Dimplex.DimplexControl.apk --build-dir d:\a\1\b/UITest_UAT/test-assembly --uitest-tools-dir d:\a\1\s/DimplexControl/Code/packages/Xamarin.UITest.2.2.7/tools --include-category Schedules --include-category ServiceEngineer --include-category UserManagement --include-category ZoneManagement --quiet is invalid
##[debug]rc:1
##[debug]success:false
##[debug]task result: Failed
##[error]Error: d:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd failed with return code: 1
##[debug]Processed: ##vso[task.issue type=error;]Error: d:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd failed with return code: 1
##[debug]Processed: ##vso[task.complete result=Failed;]Error: d:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd failed with return code: 1
##[section]Finishing: Test with Visual Studio App Center

This build was working on Friday, however I have not added in the parameter --quiet anywhere in my build steps so I'm not sure where this parameter has come from and how I can remove it.

**Comment by Brosten** [comment] 2019-11-12 10:14
I don't Think the --quiet is the problem. It's added from the DevOps build step script I guess.
Do you run the test on a build or release-pipeline? 
If it's on a separate release-pipeline, it's really easy to switch to running it on a hosted Mac instead of a hosted Windows machine. Then it will work.

You could run your build step for Android on hosted mac as well, but I Think that needs some more Changes...

**Comment by joabalea** [comment] 2019-11-18 01:54
Duplicate of #696

**Closed by joabalea** 2019-11-18 01:54 UTC
Labels: question
