### ISSUE TITLE
Updates released with --outputDir option loses codesign signature

### ISSUE THREAD

**Issue by Liampronan** [Microsoft/appcenter-cli#456] opened 2018-06-21 18:58 UTC
I'm running into a similar issue that I came across in the codepush-cli repo -- originally described here: https://github.com/Microsoft/code-push/issues/544. To summarize, when I try to build a react-native bundle to a custom folder and then attempt to release the signed folder with `codepush release`, my clients with the associated public key can't download the build; the newly released build is uploaded to codepush, but clients show the `Error! Public key was provided but there is no JWT signature within app bundle to verify` error. I can successfully sign/upload/download builds without custom folder path `release-react`. My use case for the custom build path is that it's the only way I can seem to support OTA assets, e.g., images.

**first step - build bundle to custom folder:** `react-native bundle --platform android --entry-file index.android.js --dev false --bundle-output ./release/android/index.android.bundle --sourcemap-output ./release/android/main.android.bundle.map --assets-dest ./release/android`

**second step - release custom folder using signed key:** `appcenter codepush release -a Digit/Digit-Android -d Staging -r 100 -c ./release/android/ -t 2.25 --private-key-path ./code_push_signing_key.pem --token $CODE_PUSH_CLI_TOKEN`

here's a PR that looks to have fixed it but I am running latest cli version (`app-center -v` yields `appcenter version 1.0.17`) https://github.com/Microsoft/appcenter-cli/pull/346.

when I run `release-react` without a custom folder path, I can successully release with the private-ke-signing: `appcenter codepush release-react -a Digit/Digit-Android -d Staging -r 100 --private-key-path ./code_push_signing_key.pem --entry-file index.android.js --sourcemapOutput ./release/main.android.bundle.map --token $CODE_PUSH_CLI_TOKEN`

Any thoughts on this?

**Comment by amchew** [comment] 2018-06-22 18:22
Hey @Liampronan, the PR that looks to have fixed the issue is in v1.0.8 and your version v1.0.17 is the latest version. We're investigating this. FYI @Zakeelm

**Comment by Liampronan** [comment] 2018-06-22 18:31
thanks! it's very possible I'm doing something wrong. for now I am just using the `release-react` cmd and falling back to base64 encoding images in OTA updates

**Comment by Zakeelm** [comment] 2018-06-25 21:41
Hey there! 

@alexandergoncharov will be looking into this and investigating. He'll keep you posted on the status of this as he learns more about the issue.

**Comment by alexandergoncharov** [comment] 2018-07-26 17:03
Hi all,

Sorry for delay. Fix still in progress. This fix require implementing additional logic and more time for this.

**Comment by alexandergoncharov** [comment] 2018-08-10 09:02
Hi @Liampronan ,

I implemented fix for this issue. Could you please test it?
For this you should do next steps:
1) Download changes from https://github.com/Microsoft/appcenter-cli/pull/466
2) `npm install`
3) `npm run build`
4) `node dist/index.js codepush release <args...>`

Please let me know about your results or you have any questions.

**Comment by amchew** [comment] 2018-08-15 21:37
Thanks @alexandergoncharov !

Hi @Liampronan , thanks for letting us know about the issue, and the fix is in [#466](https://github.com/Microsoft/appcenter-cli/pull/466). Could you please test this out?

**Comment by Liampronan** [comment] 2018-08-15 21:44
thanks so much! i'm on working on some other things atm -- the PR code looks good to me :) 

i ended up implementing codepush without it so may take a bit to come back and retry. thanks again!!

**Comment by amchew** [comment] 2018-08-15 21:47
Cool, @Liampronan ! 

We apologize that you had to implement codepush without the fix (argh). Do try again with the new fix when you get to it, and feel free to reach out again if you have questions.

I'll be closing this ticket for now. 
Amanda

**Closed by amchew** 2018-08-15 21:47 UTC
Labels: CodePush
