### ISSUE TITLE
Portal Helper produces invalid URLs for orgs

### ISSUE THREAD

**Issue by jp-andre** [microsoft/appcenter-cli#764] opened 2020-03-25 12:10 UTC
It assumes the app is from a user and adds `/users/` to the generated URLs.

**Comment by AmasiaNalbandian** [comment] 2021-10-13 01:43
Hi @DmitriyKirakosyan 

Do you have an idea how to reproduce this? I was able to successfully create an app in the cli, and was not given a URL for the app. Any tips should help find the source faster - thanks in advance.

**Comment by DmitriyKirakosyan** [comment] 2021-10-13 15:52
Hi @AmasiaNalbandian 

Please check https://github.com/microsoft/appcenter-cli/blame/master/src/util/portal/portal-helper.ts#L9. `getPortalBuildLink` doesn't take into account whether it is a user or an org. It is used in these places:
https://github.com/microsoft/appcenter-cli/blob/d7edaf551748c2e1c036cba795a5260bbf284f2e/src/commands/build/branches/lib/format-build.ts#L29
https://github.com/microsoft/appcenter-cli/blob/d7edaf551748c2e1c036cba795a5260bbf284f2e/src/commands/build/queue.ts#L40

I think `getPortalBuildLink` can have an additional param called `isOrg` like it is done in https://github.com/microsoft/appcenter-cli/blame/master/src/util/portal/portal-helper.ts#L12.

Additionally, I'm not 100% sure we need these changes at all. For example, if you try to navigate to a build, which was created in an org by url `https://appcenter.ms/users/<org-name>/apps/<app-name/build/branches/<branch>/builds/<build-number>`, you will see that the url is redirecting to `https://appcenter.ms/orgs/...`. I think the same happen for users as well.
So my point is, if the fix is easy to do, then we can go ahead and fix this. If it requires more complicated logic and changes in multiple files, I would rather close the issue as "not a bug".

**Comment by AmasiaNalbandian** [comment] 2021-11-05 16:35
Hi @DmitriyKirakosyan I explored into this and the objects being used for both methods are different. There would have to be a lot of refactoring in several files to implement the change. I believe if there is redirection implemented to cover this case, we can go ahead and just close this.

**Comment by DmitriyKirakosyan** [comment] 2021-11-06 16:25
Thank you @AmasiaNalbandian for the investigation. Absolutely agree, let's close it then.
If anyone encounters this issue in future, we will reopen the issue and think how to fix it properly.

So, closing for now.

**Closed by DmitriyKirakosyan** 2021-11-06 16:25 UTC
Labels: bug, good first issue
