### ISSUE TITLE
Occasionally server response 404 when I use "appcenter codepush release-cordova"

### ISSUE THREAD

**Issue by sectionDayongtek** [microsoft/appcenter-cli#1597] opened 2021-08-31 02:28 UTC
I use TeamCity to build my Corodva Android Project, and use cordova-plugin-code-push in App.

Today, TeamCity get an error, appcenter server response 404, when command executed at "appcenter codepush release-cordova" or "appcenter codepush deployment list".

At TeamCity I have 10 projects use cordova-plugin-code-push. These projects would build everyday, if git has changed. Today 3 projects get appcenter server response error 404, but others is fine.

And then I rebuild these 3 projects, all passed. No one get 404.

Is this server problem? What should I do?

Thanks.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - No, some times "appcenter codepush release-cordova", some times "appcenter codepush deployment list"
2. Which version of the App Center CLI are you using?
    - 2.10.0
3. Which OS version did you experience the issue on?
    - Windows Server 2016 Datacenter Version 1607
4. What command line/shell are you using?
    - not sure
5. Cordova Project Info?
    - "code-push": "^3.0.1"
    - "cordova": "^9.0.0"
    - "cordova-android": "^8.1.0"
    - "cordova-plugin-code-push": "^1.13.1"
6. What version of Node.js and NPM/Yarn are you using?
    - node v12.18.0, npm 6.14.4
6. Additionally, you can provide verbose logs of a CLI command by using `DEBUG="appcenter-cli:*"` before the command
(Following time is GMT +8)

First project Commad log, Date：2021/08/30
[21:37:59]> appcenter apps get-current --debug && appcenter apps set-current {UserName}/{ProjectName} --debug && appcenter codepush release-cordova -d Production -m --description "TeamCity build counter: 271" --disable-duplicate-release-error --debug
[21:37:59]
[21:38:46]Using appcenter-cli version: 2.10.0
[21:38:46]{UserName}/{LastProjectName}
[21:38:49]Using appcenter-cli version: 2.10.0
[21:38:49]logFilter, request: {
[21:38:49]  "rawResponse": false,
[21:38:49]  "queryString": {},
[21:38:49]  "url": "https://api.appcenter.ms/v0.1/apps",
[21:38:49]  "method": "GET",
[21:38:49]  "headers": {
[21:38:49]    "Content-Type": "application/json; charset=utf-8",
[21:38:49]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:38:49]    "x-api-token": "{Token}",
[21:38:49]    "internal-request-source": "cli",
[21:38:49]    "diagnostic-context": "{diagnostic-context}",
[21:38:49]    "cli-command-name": "apps set-current"
[21:38:49]  },
[21:38:49]  "body": null
[21:38:49]}
[21:38:50]Response status code: 200
[21:38:50]Body: {lots of project info}
[21:38:56]Using appcenter-cli version: 2.10.0
[21:38:56]logFilter, request: {
[21:38:56]  "rawResponse": false,
[21:38:56]  "queryString": {},
[21:38:56]  "url": "https://api.appcenter.ms/v0.1/apps/{UserName}/{ProjectName}/deployments/Production",
[21:38:56]  "method": "GET",
[21:38:56]  "headers": {
[21:38:56]    "Content-Type": "application/json; charset=utf-8",
[21:38:56]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:38:56]    "x-api-token": "{Token}",
[21:38:56]    "internal-request-source": "cli",
[21:38:56]    "diagnostic-context": "{diagnostic-context}",
[21:38:56]    "cli-command-name": "codepush release-cordova"
[21:38:56]  },
[21:38:56]  "body": null
[21:38:56]}
[21:38:57]Response status code: 404
[21:38:57]Body: Deployment "Production" does not exist.
[21:38:57]Error: Deployment "Production" does not exist.

2nd project Commad log, Date：2021/08/30
[21:46:04]> appcenter apps get-current --debug && appcenter apps set-current {UserName}/{ProjectName} --debug && appcenter codepush release-cordova -d Production -m --description "TeamCity build counter: 287" --disable-duplicate-release-error --debug
[21:46:04]
[21:46:06]Using appcenter-cli version: 2.10.0
[21:46:06]{UserName}/{LastProjectName}
[21:46:09]Using appcenter-cli version: 2.10.0
[21:46:09]logFilter, request: {
[21:46:09]  "rawResponse": false,
[21:46:09]  "queryString": {},
[21:46:09]  "url": "https://api.appcenter.ms/v0.1/apps",
[21:46:09]  "method": "GET",
[21:46:09]  "headers": {
[21:46:09]    "Content-Type": "application/json; charset=utf-8",
[21:46:09]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:46:09]    "x-api-token": "{Token}",
[21:46:09]    "internal-request-source": "cli",
[21:46:09]    "diagnostic-context": "{diagnostic-context}",
[21:46:09]    "cli-command-name": "apps set-current"
[21:46:09]  },
[21:46:09]  "body": null
[21:46:09]}
[21:46:10]Response status code: 200
[21:46:10]Body: {lots of project info}
[21:46:13]Using appcenter-cli version: 2.10.0
[21:46:13]logFilter, request: {
[21:46:13]  "rawResponse": false,
[21:46:13]  "queryString": {},
[21:46:13]  "url": "https://api.appcenter.ms/v0.1/apps/{UserName}/{ProjectName}/deployments/Production",
[21:46:13]  "method": "GET",
[21:46:13]  "headers": {
[21:46:13]    "Content-Type": "application/json; charset=utf-8",
[21:46:13]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:46:13]    "x-api-token": "{Token}",
[21:46:13]    "internal-request-source": "cli",
[21:46:13]    "diagnostic-context": "{diagnostic-context}",
[21:46:13]    "cli-command-name": "codepush release-cordova"
[21:46:13]  },
[21:46:13]  "body": null
[21:46:13]}
[21:46:14]Response status code: 200
[21:46:14]Body: {"name":"Production","key":"{KEY}","latest_release":{"target_binary_range":"1.1.13","blob_url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}","description":"TeamCity build counter: 285","is_disabled":false,"is_mandatory":true,"label":"v174","package_hash":"{package_hash}","released_by":"{EMAIL}","release_method":"Upload","rollout":100,"size":14081173,"upload_time":1629964019873,"diff_package_map":{"{diff_package_map_KEY}":{"size":410880,"url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}"},"{diff_package_map_KEY}":{"size":396045,"url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}"},"{diff_package_map_KEY}":{"size":150597,"url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}"},"{diff_package_map_KEY}":{"size":138227,"url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}"},"{diff_package_map_KEY}":{"size":1978,"url":"https://codepush.blob.core.windows.net/storagev2/{HASH_CODE?}"}}}}
[21:46:14]logFilter, request: {
[21:46:14]  "rawResponse": false,
[21:46:14]  "queryString": {},
[21:46:14]  "url": "https://api.appcenter.ms/v0.1/apps/{UserName}/{ProjectName}",
[21:46:14]  "method": "GET",
[21:46:14]  "headers": {
[21:46:14]    "Content-Type": "application/json; charset=utf-8",
[21:46:14]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:46:14]    "x-api-token": "{Token}",
[21:46:14]    "internal-request-source": "cli",
[21:46:14]    "diagnostic-context": "{diagnostic-context}",
[21:46:14]    "cli-command-name": "codepush release-cordova"
[21:46:14]  },
[21:46:14]  "body": null
[21:46:14]}
[21:46:15]Response status code: 200
[21:46:15]Body: {"id":"{id}","app_secret":"{app_secret}","description":null,"display_name":"{ProjectName}","name":"{ProjectName}","os":"Android","platform":"Cordova","origin":"appcenter","icon_url":"https://coreservicesstorgeprod.blob.core.windows.net/app-avatar-container/{HASH_CODE?}?st=2021-08-27T12%3A48%3A33Z&se=2021-09-10T13%3A48%3A33Z&sp=r&sv=2018-03-28&sr=b&sig={sig}","created_at":"2020-09-02T01:58:07.000Z","updated_at":"2020-09-02T01:58:08.000Z","release_type":"Production","owner":{"id":"{id}","avatar_url":null,"display_name":"","email":"{EMAIL}","name":"{UserName}","type":"user"},"azure_subscription":null,"member_permissions":["manager"]}
[21:46:15]Running "cordova prepare" command:
...
...
...
[21:46:19]Releasing update contents to CodePush:
[21:46:19]
[21:46:26]logFilter, request: {
[21:46:26]  "rawResponse": false,
[21:46:26]  "queryString": {},
[21:46:26]  "url": "https://api.appcenter.ms/v0.1/apps/{UserName}/{ProjectName}/deployments/Production/uploads",
[21:46:26]  "method": "POST",
[21:46:26]  "headers": {
[21:46:26]    "Content-Type": "application/json; charset=utf-8",
[21:46:26]    "user-agent": "appcenterCli/2.10.0 NodeJS/v12.18.0 win32/10.0.14393",
[21:46:26]    "x-api-token": "{Token}",
[21:46:26]    "internal-request-source": "cli",
[21:46:26]    "diagnostic-context": "{diagnostic-context}",
[21:46:26]    "cli-command-name": "codepush release-cordova"
[21:46:26]  },
[21:46:26]  "body": null
[21:46:26]}
[21:46:27]Response status code: 404
[21:46:27]Body: Deployment "Production" does not exist.
[21:46:27]Error: Deployment "Production" does not exist.

3rd project Commad log, Date：2021/08/31
This project I don't use --debug flag, but it seems like the same status
[07:52:59]> appcenter codepush deployment list > platforms/codePushVersion.txt
[07:52:59]
[07:53:04]npm ERR! code ELIFECYCLE
[07:53:04]npm ERR! errno 4
[07:53:04]npm ERR! JSMobile@1.0.0 printVersion: `appcenter codepush deployment list > platforms/codePushVersion.txt`
[07:53:04]npm ERR! Exit status 4
[07:53:04]npm ERR! 
[07:53:04]npm ERR! Failed at the JSMobile@1.0.0 printVersion script.
[07:53:04]npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[07:53:04]
[07:53:04]npm ERR! A complete log of this run can be found in:
[07:53:04]npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-08-30T23_53_04_661Z-debug.log
[07:53:04]Process exited with code 4

**Comment by aleksandr-dorofeev** [comment] 2021-08-31 12:11
Hi, @sectionDayongtek 
Thank you for reaching out to us!
We will sync with the backend team to check this issue and get to you with an update.

**Comment by aleksandr-dorofeev** [comment] 2021-09-01 14:34
Hello, @sectionDayongtek 
I got the answer from the backend team! Tell me, please, can you reproduce it locally? Does it still happen on you CI or it is gone completely? Can you also share your app name, app owner, so we could check the logs? Since this information is confidential, I would suggest to contact support from appcenter.ms (question mark -> contact support), or send it me directly on v-adorofeev@microsoft.com.

At this moment it is unclear what could cause this issue. We will investigate it further with the info that you provide and let you know if we find anything useful.

I'm closing this issue for now, since it is not reproducing anymore. Please reopen if you face the issue again.

**Closed** 2021-09-01 17:46 UTC
