### ISSUE TITLE
Appcenter codepush error: Failed to release a CodePush update

### ISSUE THREAD

**Issue by carloscuesta** [microsoft/appcenter-cli#1249] opened 2021-01-28 16:22 UTC
Hello! :wave:

I recently bumped `appcenter-cli` from `1.1.20` on a project to `2.7.3` version and now our `appcenter codepush release-react` command is failing.

If I'm not mistaken all the options we're passing are correct:

```
appcenter codepush release-react -a ulabox-mobile/ulabox-android -d Production -o bundle --disable-duplicate-release-error -t $(node -p "require('./package.json').version")
```

I tried using the `--debug` flag but no other info was provided:

```
info Writing bundle output to:, bundle/CodePush/index.android.bundle
info Writing sourcemap output to:, bundle/CodePush/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 67 asset files
info Done copying assets
Error: Failed to release a CodePush update.
```

Thanks!

**Comment by carloscuesta** [comment] 2021-01-29 08:32
I've been testing various `Releases` of the `appcenter-cli` and I found out that [`2.1.0`](https://github.com/microsoft/appcenter-cli/releases/tag/v2.1.0) is the last version that works with the command that I copied at the issue.

Starting from [`2.1.1`](https://github.com/microsoft/appcenter-cli/releases/tag/v2.1.1) and above all the versions fail to release the CodePush update.

**Comment by andreidubov** [comment] 2021-01-29 10:01
Hey @carloscuesta,

This problem is not reproducible on my side in the CodePush-Example app. Therefore, can you provide additional information for us:

* Which version of `react-native` and `react-native-code-push` are you using?

* Are you using Hermes in your application?

**Comment by carloscuesta** [comment] 2021-01-29 10:03
Sure!

- `react-native-code-push`: `2.7.3`
- `react-native`: `0.60`
- Not using hermes

**Comment by andreidubov** [comment] 2021-01-29 10:39
@carloscuesta,  Excuse me, maybe there was some misunderstanding, you probably wrote the version of `appcenter-cli: v2.7.3`. Because there is no `react-native-code-push` with this version. Could you clarify the version of [code-push-react-native](https://github.com/microsoft/react-native-code-push) used in your project?

**Comment by carloscuesta** [comment] 2021-01-29 10:43
Sure, I edited the comment, sorry for the confusion 😅

**Comment by andreidubov** [comment] 2021-01-29 11:25
@carloscuesta, May I ask you to provide a **project.ext.ract** value in `android/app/build.gradle` file if possible?
f.e. my build.gradle: 
![Screen Shot 2021-01-29 at 2 24 00 PM](https://user-images.githubusercontent.com/58589743/106269541-ad014200-623d-11eb-822f-5360064bde7f.png)

**Comment by carloscuesta** [comment] 2021-01-29 11:33
It's not defined the `project.ext.react` on the `android/app/build.gradle`

**Comment by andreidubov** [comment] 2021-01-29 11:46
@carloscuesta  So, I managed to reproduce the problem, we added it to our backlog, in fact, there is a workaround for you: 

Add this code in your `android/app/build.gradle`
```
project.ext.react = [
   enableHermes: false
]
```

I will let you know when this is fixed in the new version, thanks.

**Comment by carloscuesta** [comment] 2021-01-29 11:50
I have been able to release a CodePush version with the workaround you suggested! 👏🏼 

Thanks for your time I will look forward to the release of the fix ❤️

**Closed** 2021-02-22 08:31 UTC
Labels: CodePush, bug
