### ISSUE TITLE
Add silent option to distribute release command

### ISSUE THREAD

**Issue by thiemf** [microsoft/appcenter-cli#589] opened 2019-05-22 13:11 UTC
Hi,

would it be possible to add a "silent" option to the "distrbute release" command? With the same behaviour as the existing "--silent" option for the "distribute releases add-destination" command. 
Reason behind is that we would like to not send any notification emails to testers when distributing new releases since they usually get confused by those emails. 

Currently we are using the following workaround to achieve the same:
1. Upload release using "distribute release", specfiying a dummy, empty distribution group
2. Add additional groups using command "distribute releases add-destination", with the "--silent" option

If we could have a "silent" option directly in the "distribute release" command that would make our life a bit easier. 

Thanks,
Matthias

**Comment by jpeg-ms** [comment] 2019-09-25 07:35
This looks like a duplicate of #602.

**Closed by jpeg-ms** 2019-09-25 07:35 UTC

**Comment by thiemf** [comment] 2019-09-25 17:15
Why is the issue with more votes (7) closed and the one with fewer votes (1) is left open ?

**Comment by jpeg-ms** [comment] 2019-09-25 21:57
@thiemf Sorry I closed this issue, as the other one simply had more context to it, including a PR. We are going to resolve it very soon, I did not mean to ignore your request!

**Comment by thiemf** [comment] 2019-10-01 15:14
Thanks, makes sense. We just tried the new 2.2.0 release with this feature and it works nice :-) 
Thank you!
